-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Sep 17, 2015 at 12:24 AM
-- Server version: 5.6.21
-- PHP Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `akreditasi`
--

-- --------------------------------------------------------

--
-- Table structure for table `group`
--

CREATE TABLE IF NOT EXISTS `group` (
`id` int(10) unsigned NOT NULL,
  `nama` varchar(45) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `group`
--

INSERT INTO `group` (`id`, `nama`) VALUES
(1, 'Admin'),
(2, 'Asesor'),
(3, 'Mahasiswa');

-- --------------------------------------------------------

--
-- Table structure for table `identitas`
--

CREATE TABLE IF NOT EXISTS `identitas` (
`id` int(10) unsigned NOT NULL,
  `progli` varchar(50) NOT NULL,
  `sekolah` varchar(30) NOT NULL,
  `nss` varchar(30) NOT NULL,
  `alamat` varchar(150) NOT NULL,
  `kec` varchar(50) NOT NULL,
  `kab` varchar(50) NOT NULL,
  `provinsi` varchar(50) NOT NULL,
  `kodepos` varchar(10) NOT NULL,
  `telp` varchar(25) NOT NULL,
  `email` varchar(50) NOT NULL,
  `status` tinyint(3) unsigned NOT NULL,
  `yayasan` varchar(70) NOT NULL,
  `akte` varchar(50) NOT NULL,
  `tahunb` int(10) unsigned NOT NULL,
  `statusa` varchar(20) NOT NULL,
  `visi` varchar(600) NOT NULL,
  `misi` varchar(600) NOT NULL,
  `tujuans` varchar(600) NOT NULL,
  `tujuanp` varchar(600) NOT NULL,
  `user_id` int(10) unsigned NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `identitas`
--

INSERT INTO `identitas` (`id`, `progli`, `sekolah`, `nss`, `alamat`, `kec`, `kab`, `provinsi`, `kodepos`, `telp`, `email`, `status`, `yayasan`, `akte`, `tahunb`, `statusa`, `visi`, `misi`, `tujuans`, `tujuanp`, `user_id`) VALUES
(7, 'Akuntansi', 'SMK N 1 Bukateja', '123123123123', 'Bukateja, Purbalingga', 'Bukateja', 'Purbalingga', 'Jawa Tengah', '53392', '028124123', 'smkn1bukateja@gmail.com', 2, 'BKTJ', '12091239123', 1991, '2001', 'adassd', 'asdasd', 'jj', 'Tujuan hidupku adalah untuk mengarungi samudra bahtera rumah tangga', 6),
(8, 'Teknik Komputer dan Jaringan', 'SMK N 1 Purbalingga', '12391231231312', 'asdas', 'asda', 'asdad', 'adasd', 'asdasd', 'rfr', 'dayzramly@gmail.com', 1, 'asasd', 'asdasdas', 2010, 'adasd', 'asdasdas', 'asdasdas', 'asdasdas', 'asdasdas', 7);

-- --------------------------------------------------------

--
-- Table structure for table `jawaban`
--

CREATE TABLE IF NOT EXISTS `jawaban` (
`id` int(10) unsigned NOT NULL,
  `jawaban` text NOT NULL,
  `selesai` tinyint(4) NOT NULL,
  `user_id` int(10) unsigned NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `jawaban`
--

INSERT INTO `jawaban` (`id`, `jawaban`, `selesai`, `user_id`) VALUES
(3, '{"2":{"no":"2","jawaban":"1","file":"\\/upload\\/upload_Booking_2_isipenumpang.png"},"3":{"no":"3","jawaban":"3","file":"\\/upload\\/upload_booking_4_review.png"},"1":{"no":"1","jawaban":"2","file":"\\/upload\\/upload_Filter.png"},"4":{"no":"4","jawaban":"3","file":"\\/upload\\/upload_booking_9_unduh_eticket.png"},"6":{"no":"6","jawaban":"2","file":"\\/upload\\/upload_nav-sprite6.bbe9ad55faee.png"},"7":{"no":"7","jawaban":"2","file":"\\/upload\\/upload_nav-sprite6.bbe9ad55faee.png"},"8":{"no":"8","jawaban":"3"},"5":{"no":"5","jawaban":"2"}}', 1, 6),
(4, '{"1":{"no":"1","jawaban":"3","file":"\\/upload\\/upload_2015-07-26_131818.png"},"184":{"no":"184","jawaban":"2","file":"\\/upload\\/upload_nav-sprite6.bbe9ad55faee.png"},"2":{"no":"2","jawaban":"2"},"3":{"no":"3","jawaban":"2"}}', 0, 7);

-- --------------------------------------------------------

--
-- Table structure for table `pertanyaan`
--

CREATE TABLE IF NOT EXISTS `pertanyaan` (
`id` int(10) unsigned NOT NULL,
  `pertanyaan` text NOT NULL,
  `pilihan` text NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=186 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `pertanyaan`
--

INSERT INTO `pertanyaan` (`id`, `pertanyaan`, `pilihan`) VALUES
(1, 'Program keahlian melaksanakan kurikulum berdasarkan muatan Kurikulum Tingkat Satuan Pendidikan (KTSP)', '["Melaksanakan kurikulum berdasarkan 9 muatan KTSP","Melaksanakan kurikulum berdasarkan 8 muatan KTSP","Melaksanakan kurikulum berdasarkan 7 muatan KTSP","Melaksanakan kurikulum berdasarkan 6 atau kurang muatan KTSP","Tidak melaksanakan KTSP "]'),
(2, 'Program keahlian mengembangkan kurikulum bersama-sama Tim Pengembang Kurikulum berpedoman pada panduan penyusunan kurikulum yang dibuat oleh BSNP.', '["Bersama seluruh guru mata pelajaran dalam Program keahlian, Ketua program keahlian, Kepala Sekolah/Madrasah, Nara sumber dari Dunia Usaha atau Dunia Industri (DU/DI), konselor, komite sekolah/madrasah, dan penyelenggara lembaga pendidikan","Bersama seluruh guru mata pelajaran dalam program keahlian, Ketua program keahlian, Kepala Sekolah/Madrasah, Nara sumber dari Dunia Usaha atau Dunia Industri (DU/DI), dan konselor","Bersama seluruh guru mata pelajaran dalam program keahlian, Ketua program keahlian, Kepala Sekolah/Madrasah, dan Nara sumber dari Dunia Usaha atau Dunia Industri (DU/DI)","Bersama seluruh guru mata pelajaran dalam program keahlian, Ketua program keahlian, dan Kepala Sekolah/Madrasah","Tidak mengembangkan kurikulum "]'),
(3, 'Program keahlian mengembangkan kurikulum melalui mekanisme penyusunan KTSP.', '["Mekanisme pengembangan kurikulum dilakukan melalui 7 kegiatan pokok","Mekanisme pengembangan kurikulum dilakukan melalui 5 atau 6 kegiatan pokok","Mekanisme pengembangan kurikulum dilakukan melalui 3 atau 4 kegiatan pokok","Mekanisme pengembangan kurikulum dilakukan melalui 1 atau 2 kegiatan pokok","Tidak mengembangkan kurikulum   "]'),
(4, 'Program keahlian mengembangkan kurikulum dengan menggunakan prinsip pengembangan KTSP', '["Melaksanakan 7 prinsip pengembangan KTSP","Melaksanakan 5-6 prinsip pengembangan KTSP","Melaksanakan 3-4 prinsip pengembangan KTSP","Melaksanakan 1-2 prinsip pengembangan KTSP","Tidak mengembangkan kurikulum "]'),
(5, 'Program keahlian menyusun kurikulum muatan lokal dan kurikulum berbasis pendidikan karakter dengan melibatkan berbagai pihak.', '["Menyusun dengan melibatkan 7 pihak atau lebih","Menyusun dengan melibatkan 5-6 pihak","Menyusun dengan melibatkan 3-4 pihak","Menyusun dengan melibatkan 1-2 pihak","Tidak menyusun kurikulum muatan lokal "]'),
(6, 'Program keahlian melaksanakan program pengembangan diri dalam bentuk kegiatan ekstrakurikuler.', '["Melaksanakan 7 jenis atau lebih kegiatan ekstrakurikuler","Melaksanakan 5-6 kegiatan ekstrakurikuler","Melaksanakan 3-4 kegiatan ekstrakurikuler","Melaksanakan 1-2 kegiatan ekstrakurikuler","Tidak melaksanakan kegiatan ekstrakurikuler   "]'),
(7, 'Program keahlian melaksanakan program pengembangan diri dalam bentuk kegiatan konseling.', '["Melaksanakan 4 atau lebih jenis kegiatan konseling","Melaksanakan 3 jenis kegiatan konseling","Melaksanakan 2 jenis kegiatan konseling","Melaksanakan 1 jenis kegiatan konseling","Tidak melaksanakan kegiatan konseling "]'),
(8, 'Program keahlian melaksanakan program Praktik Kerja di Dunia Usaha / Industri (Prakerin) sesuai dengan ketentuan yang berlaku', '["Program dilaksanakan selama 3 bulan atau lebih dan mengikuti jam kerja karyawan/pegawai","Program dilaksanakan selama 3 bulan atau lebih, tetapi tidak mengikuti jam kerja karyawan/pegawai","Program dilaksanakan kurang dari 3 bulan, tetapi mengikuti jam kerja karyawan/pegawai","Program dilaksanakan kurang dari 3 bulan, dan tidak mengikuti jam kerja karyawan/pegawai","Program Praktik Kerja tidak dilaksanakan "]'),
(9, 'Program keahlian menerapkan kegiatan pembelajaran sesuai dengan ketentuan beban belajar yang tertuang pada Permendiknas Nomor 22 Tahun 2006.', '["Satu jam pembelajaran tatap muka selama 45 menit, jumlah jam pembelajaran per minggu minimal 36 jam, dan jumlah minggu efektif per tahun minimal 38 minggu","Satu jam pembelajaran tatap muka selama 45 menit, jumlah jam pembelajaran per minggu minimal 36 jam, dan jumlah minggu efektif per tahun kurang dari 38 minggu","Satu jam pembelajaran tatap muka selama 45 menit, jumlah jam pembelajaran per minggu kurang dari 36 jam, dan jumlah minggu efektif per tahun kurang dari 38 minggu","Satu jam pembelajaran tatap muka kurang dari 45 menit, jumlah jam pembelajaran per minggu kurang dari 36 jam, dan jumlah minggu efektif per tahun kurang dari 38 minggu","Tidak menerapkan ketentuan beban belajar yang ditetapkan Kemdikbud   "]'),
(10, 'Guru mata pelajaran memberikan penugasan terstruktur dan kegiatan mandiri tidak terstruktur untuk mencapai kompetensi yang diberikan kepada siswa maksimal 60% dari alokasi waktu tiap mata pelajaran.', '["91%-100% guru mata pelajaran memberikan penugasan terstruktur dan kegiatan mandiri tidak terstruktur","81%-90% guru mata pelajaran memberikan penugasan terstruktur dan kegiatan mandiri tidak terstruktur","71%-80% guru mata pelajaran memberikan penugasan terstruktur dan kegiatan mandiri tidak terstruktur","61%-70% guru mata pelajaran memberikan penugasan terstruktur dan kegiatan mandiri tidak terstruktur","Kurang dari 61% guru mata pelajaran memberikan penugasan terstruktur dan kegiatan mandiri tidak terstruktur "]'),
(11, 'Program keahlian melaksanakan proses pembelajaran mata pelajaran kewirausahaan berdasarkan ketentuan dalam struktur kurikulum.', '["Berdasarkan pada silabus, RPP, dan alokasi waktu 192 jam pelajaran","Berdasarkan pada silabus, tidak menggunakan RPP, dan alokasi waktu 192 jam pelajaran","Berdasarkan pada silabus, RPP, dan alokasi waktu kurang dari 192 jam pelajaran","Berdasarkan pada silabus, tidak ada RPP, dan alokasi waktu kurang dari 192 jam pelajaran","Tidak berdasarkan pada silabus, tidak ada RPP, dan alokasi waktu kurang dari 192 jam pelajaran "]'),
(12, 'Program keahlian memanfaatkan Teknologi Informasi dan Komunikasi (TIK) dalam pembelajaran seluruh mata pelajaran', '["Lebih dari 90% mata pelajaran memanfaatkan TIK.","81%-90% mata pelajaran memanfaatkan TIK.","71%-80% mata pelajaran memanfaatkan TIK.","61%-70% mata pelajaran memanfaatkan TIK.","Kurang dari 61% mata pelajaran memanfaatkan TIK.   "]'),
(13, 'KTSP disahkan oleh Kepala Sekolah/Madrasah dengan memperhatikan pertimbangan Komite Sekolah/Madrasah atau penyelenggara pendidikan yang disetujui oleh Dinas Pendidikan Provinsi atau Kanwil Kemenag.', '["KTSP disahkan oleh Kepala Sekolah/Madrasah dengan memperhatikan pertimbangan Komite Sekolah/Madrasah atau penyelenggara pendidikan, dan disetujui oleh Dinas Pendidikan Provinsi atau Kanwil Kemenag","KTSP disahkan oleh Kepala Sekolah/Madrasah dan disetujui oleh Dinas Pendidikan Provinsi atau Kanwil Kemenag","KTSP disahkan oleh Kepala Sekolah/Madrasah dengan memperhatikan pertimbangan Komite Sekolah/Madrasah atau penyelenggara pendidikan","KTSP disahkan oleh Kepala Sekolah/Madrasah","KTSP tidak disahkan "]'),
(14, 'Program keahlian mengembangkan silabus secara mandiri atau cara lainnya berdasarkan standar isi, standar kompetensi lulusan, dan panduan penyusunan KTSP.', '["Mengembangkan silabus melalui kelompok guru mata pelajaran dalam sebuah sekolah/madrasah","Mengembangkan silabus oleh masing-masing guru mata pelajaran","Mengembangkan silabus melalui kelompok guru dari beberapa sekolah/madrasah","Mengembangkan silabus dengan mengadopsi contoh yang sudah ada","Tidak mengembangkan silabus "]'),
(15, 'Guru mengembangkan silabus sesuai dengan langkah-langkah pengembangan', '["Guru melaksanakan 7 langkah","Guru melaksanakan 5-6 langkah","Guru melaksanakan 3-4 langkah","Guru melaksanakan 1-2 langkah","Guru tidak mengembangkan silabus   "]'),
(16, 'Program keahlian menjabarkan Standar Kompetensi (SK) dan Kompetensi Dasar (KD) ke dalam indikator-indikator untuk setiap mata pelajaran.', '["13 mata pelajaran atau lebih telah sesuai antara SK, KD, dan indikator-indikatornya","9-12 mata pelajaran telah sesuai antara SK, KD, dan indikatorindikatornya","5-8 mata pelajaran telah sesuai antara SK, KD, dan indikatorindikatornya","1-4 mata pelajaran telah sesuai antara SK, KD, dan indikatorindikatornya","Tidak ada mata pelajaran yang sesuai antara SK, KD, dan indikatorindikatornya "]'),
(17, 'Program keahlian menetapkan Kriteria Ketuntasan Minimal (KKM) 75% untuk setiap mata pelajaran.', '["6 atau lebih mata pelajaran dengan KKM 75% atau lebih","5 mata pelajaran dengan KKM 75% atau lebih","4 atau lebih mata pelajaran dengan KKM 75% atau lebih","3 atau lebih mata pelajaran dengan KKM 75% atau lebih","Kurang dari 3 mata pelajaran dengan KKM 75% atau lebih "]'),
(18, 'Program keahlian atau sekolah/madrasah memiliki kalender pendidikan yang memuat pengaturan waktu untuk kegiatan pembelajaran peserta didik selama satu tahun ajaran: (1) awal tahun pelajaran, (2) minggu efektif, (3) pembelajaran efektif, dan (4) hari libur.', '["Memuat 4 macam pengaturan waktu","Memuat 3 macam pengaturan waktu","Memuat 2 macam pengaturan waktu","Memuat 1 macam pengaturan waktu","Tidak memiliki kalender pendidikan   "]'),
(19, 'Setiap mata pelajaran memiliki Rencana Pelaksanaan Pembelajaran (RPP) dengan mengintegrasikan pendidikan karakter yang dijabarkan dari silabus.', '["13 mata pelajaran atau lebih memiliki RPP dengan mengintegrasikan pendidikan karakter yang dijabarkan dari silabus","9-12 mata pelajaran memiliki RPP dengan mengintegrasikan pendidikan karakter yang dijabarkan dari silabus","5-8 mata pelajaran memiliki RPP dengan mengintegrasikan pendidikan karakter yang dijabarkan dari silabus","1-4 mata pelajaran memiliki RPP dengan mengintegrasikan pendidikan karakter yang dijabarkan dari silabus","Tidak ada mata pelajaran memiliki RPP dengan mengintegrasikan pendidikan karakter yang dijabarkan dari silabus "]'),
(20, 'RPP disusun dengan memperhatikan 6 prinsip penyusunan.', '["91%-100% RPP sudah 6 prinsip penyusunan.","81%-90% RPP sudah 6 prinsip penyusunan.","71%-80% RPP sudah 6 prinsip penyusunan.","61%-70% RPP sudah 6 prinsip penyusunan.","Kurang dari 60% RPP sudah 6 prinsip penyusunan. "]'),
(21, 'Program keahlian melaksanakan proses pembelajaran sesuai dengan persyaratan yang ditentukan.', '["Memenuhi 4 persyaratan pelaksanaan proses pembelajaran","Memenuhi 3 persyaratan pelaksanaan proses pembelajaran","Memenuhi 2 persyaratan pelaksanaan proses pembelajaran","Memenuhi 1 persyaratan pelaksanaan proses pembelajaran","Tidak memenuhi persyaratan pelaksanaan proses pembelajaran   "]'),
(22, 'Guru melaksanakan proses pembelajaran sesuai dengan langkah-langkah pembelajaran yang tertuang dalam RPP.', '["91%-100% guru melaksanakan proses pembelajaran sesuai dengan langkah-langkah pembelajaran","81%-90% guru melaksanakan proses pembelajaran sesuai dengan langkah-langkah pembelajaran","71%-80% guru melaksanakan proses pembelajaran sesuai dengan langkah-langkah pembelajaran","61%-70% guru melaksanakan proses pembelajaran sesuai dengan langkah-langkah pembelajaran","Kurang dari 61% guru melaksanakan proses pembelajaran sesuai dengan langkah-langkah pembelajaran "]'),
(23, 'Program keahlian melaksanakan proses pembelajaran berbasis Teknologi Informasi dan Komunikasi (sesuai dengan tingkat kebutuhan Program keahliannya) dengan SDM yang memiliki kesesuaian kompetensi.', '["Pelaksanaan pembelajaran berbasis TIK dilakukan sendiri oleh pihak program keahlian dengan SDM sendiri yang memiliki kesesuaian kompetensi dan bersertifikat","Pelaksanaan pembelajaran berbasis TIK dilakukan sendiri oleh pihak program keahlian dengan mendatangkan SDM dari sekolah/madrasah lain","Pelaksanaan pembelajaran berbasis TIK dilakukan oleh pihak lain dengan sebagian SDM dari pihak program keahlian","Pelaksanaan pembelajaran berbasis TIK dilakukan oleh pihak lain (outsource)","Tidak melaksanakan pembelajaran berbasis TIK   "]'),
(24, 'Kegiatan wirausaha pada unit produksi atau business center dilakukan sebagai wahana untuk meningkatkan kompetensi siswa sesuai dengan keahliannya.', '["Kegiatan wirausaha pada unit produksi atau business center dilakukan sesuai dengan proses pembelajaran, materi program keahlian, dan aturan pengelolaan yang transparan","Kegiatan wirausaha pada unit produksi atau business center dilakukan sesuai dengan proses pembelajaran, dan materi program keahlian","Kegiatan wirausaha pada unit produksi atau business center dilakukan sesuai dengan proses pembelajaran dan aturan pengelolaan yang transparan","Kegiatan wirausaha pada unit produksi atau business center dilakukan hanya sesuai dengan proses pembelajaran.","Tidak sesuai dengan proses pembelajaran "]'),
(25, 'Program keahlian menindaklanjuti Memorandum of Understanding (MoU) kerjasama dengan DU/DI.', '["91%-100% tindaklanjut MoU melalui pelaksanaan pembelajaran","81%-90% tindaklanjut MoU melalui pelaksanaan pembelajaran","71%-80% tindaklanjut MoU melalui pelaksanaan pembelajaran","61%-70% tindaklanjut MoU melalui pelaksanaan pembelajaran","Kurang dari 61% tindaklanjut MoU melalui pelaksanaan pembelajaran "]'),
(26, 'Siswa melakukan praktik kerja pada DU/DI untuk memperoleh kompetensi keahliannya.', '["96%-100% siswa melakukan prakerin pada DU/DI yang relevan","91%-95% siswa melakukan prakerin pada DU/DI yang relevan","86%-90% siswa melakukan prakerin pada DU/DI yang relevan","81%-85% siswa melakukan prakerin pada DU/DI yang relevan","Kurang dari 81% siswa melakukan prakerin pada DU/DI yang relevan   "]'),
(27, 'Kepala sekolah/madrasah dan program keahlian melakukan pemantauan proses pembelajaran mencakup tiga tahapan yaitu: (1) perencanaan, (2) pelaksanaan, dan (3) penilaian hasil pembelajaran.', '["Mencakup 3 tahap pemantauan serta dilakukan diskusi hasil pemantauan","Mencakup 3 tahap pemantauan tanpa dilakukan diskusi hasil pemantauan","Mencakup 2 tahap pemantauan","Mencakup 1 tahap pemantauan","Tidak pernah melakukan pemantauan "]'),
(28, 'Supervisi proses pembelajaran dilakukan oleh kepala sekolah/madrasah dan ketua program keahlian dengan cara pemberian contoh, diskusi, pelatihan, dan konsultasi.', '["Melakukan supervisi proses pembelajaran melalui 4 cara","Melakukan supervisi proses pembelajaran melalui 3 cara","Melakukan supervisi proses pembelajaran melalui 2 cara","Melakukan supervisi proses pembelajaran melalui 1 cara","Tidak melakukan supervisi proses pembelajaran "]'),
(29, 'Evaluasi terhadap guru dalam proses pembelajaran dilakukan oleh kepala sekolah/madrasah dan ketua program keahlian dengan memperhatikan 4 aspek, yaitu 1) persiapan, 2) pelaksanaan, 3) evaluasi pembelajaran, dan 4) rencana tindak lanjut.', '["Evaluasi dilakukan dengan memperhatikan 4 aspek","Evaluasi dilakukan dengan memperhatikan 3 aspek","Evaluasi dilakukan dengan memperhatikan 2 aspek","Evaluasi dilakukan dengan memperhatikan 1 aspek","Tidak melakukan evaluasi   "]'),
(30, 'Kepala sekolah/madrasah dan ketua program keahlian menyampaikan hasil pengawasan (pemantauan, supervisi, dan evaluasi) proses pembelajaran kepada pemangku kepentingan.', '["Hasil pengawasan disampaikan kepada guru yang bersangkutan, dewan guru, dan pengawas sekolah/madrasah","Hasil pengawasan disampaikan kepada guru yang bersangkutan dan dewan guru","Hasil pengawasan disampaikan kepada yang bersangkutan saja","Tidak disampaikan","Tidak melakukan pengawasan "]'),
(31, 'Kepala sekolah/madrasah dan ketua program keahlian melakukan tindak lanjut terhadap hasil pengawasan proses pembelajaran.', '["91%-100% hasil pengawasan selama 1 tahun terakhir dilakukan tindak lanjut","81%-90% hasil pengawasan selama 1 tahun terakhir dilakukan tindak lanjut","71%-80% hasil pengawasan selama 1 tahun terakhir dilakukan tindak lanjut","61%-70% hasil pengawasan selama 1 tahun terakhir dilakukan tindak lanjut","Kurang dari 61% hasil pengawasan selama 1 tahun terakhir dilakukan tindak lanjut   "]'),
(32, 'Siswa memperoleh pengalaman belajar melalui kelompok mata pelajaran Iptek untuk dapat berpikir logis, kritis, kreatif, dan inovatif dalam pengambilan keputusan dan pemecahan masalah.', '["91%-100% mata pelajaran kelompok Iptek memuat tugas terstruktur","81%-90% mata pelajaran kelompok Iptek memuat tugas terstruktur","71%-80% mata pelajaran kelompok Iptek memuat tugas terstruktur","61%-70% mata pelajaran kelompok Iptek memuat tugas terstruktur","Kurang dari 61% mata pelajaran kelompok Iptek memuat tugas terstruktur "]'),
(33, 'Siswa terlibat dalam kegiatan belajar kelompok mata pelajaran Iptek yang berkaitan dengan analisis dan pemecahan masalah kompleks.', '["4 atau lebih mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran yang berkaitan dengan pemecahan masalah kompleks.","3 mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran yang berkaitan dengan pemecahan masalah kompleks.","2 mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran yang berkaitan dengan pemecahan masalah kompleks.","1 mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran yang berkaitan dengan pemecahan masalah kompleks.","Tidak ada mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran yang berkaitan dengan pemecahan masalah kompleks.   "]'),
(34, 'Siswa terlibat dalam kegiatan belajar kelompok mata pelajaran Iptek yang memiliki kemampuan untuk menganalisis gejala alam dan sosial.', '["4 atau lebih mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran untuk menganalisis gejala alam dan sosial.","3 mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran untuk menganalisis gejala alam dan sosial.","2 mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran untuk menganalisis gejala alam dan sosial.","1 mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran untuk menganalisis gejala alam dan sosial.","Tidak ada mata pelajaran kelompok Iptek dapat menunjukkan kegiatan pembelajaran untuk menganalisis gejala alam dan sosial. "]'),
(35, 'Siswa memperoleh pengalaman belajar dalam kelompok mata pelajaran Produktif dan Adaptif secara efektif.', '["Program keahlian memfasilitasi kegiatan siswa dengan memanfaatkan dan memfungsikan sumber belajar meliputi bahan ajar, buku teks, perpustakaan, laboratorium, dan internet","Program keahlian memfasilitasi kegiatan siswa dengan memanfaatkan dan memfungsikan sumber belajar meliputi bahan ajar, buku teks, perpustakaan, dan laboratorium","Program keahlian memfasilitasi kegiatan siswa dengan memanfaatkan dan memfungsikan sumber belajar meliputi bahan ajar, buku teks, dan perpustakaan","Program keahlian memfasilitasi kegiatan siswa dengan memanfaatkan dan memfungsikan sumber belajar meliputi bahan ajar dan buku teks","Program keahlian tidak pernah memfasilitasi kegiatan siswa dengan sumber belajar   "]'),
(36, 'Siswa memperoleh pengalaman belajar melalui program pembiasaan untuk mencari informasi/pengetahuan lebih lanjut dari berbagai sumber belajar dalam satu tahun terakhir.', '["Siswa menjalankan 10 kali atau lebih kegiatan pembiasaan untuk mencari informasi/pengetahuan lebih lanjut dari berbagai sumber belajar","Siswa menjalankan 7-9 kali kegiatan pembiasaan untuk mencari informasi/pengetahuan lebih lanjut dari berbagai sumber belajar","Siswa menjalankan 4-6 kali kegiatan pembiasaan untuk mencari informasi/pengetahuan lebih lanjut dari berbagai sumber belajar","Siswa menjalankan 1-3 kali kegiatan pembiasaan untuk mencari informasi/pengetahuan lebih lanjut dari berbagai sumber belajar","Siswa tidak menjalankan kegiatan pembiasaan untuk mencari informasi/pengetahuan lebih lanjut dari berbagai sumber belajar "]'),
(37, 'Siswa mengikuti kegiatan pembelajaran yang memanfaatkan lingkungan secara produktif dan bertanggung jawab dalam 1 tahun terakhir.', '["Program keahlian menjalankan 4 atau lebih kegiatan","Program keahlian menjalankan 3 kegiatan","Program keahlian menjalankan 2 kegiatan","Program keahlian menjalankan 1 kegiatan","Program keahlian tidak menjalankan kegiatan "]'),
(38, 'Siswa memperoleh pengalaman mengekspresikan diri melalui kegiatan seni dan budaya dalam 1 tahun terakhir.', '["Siswa mengekspresikan diri melalui 4 atau lebih kegiatan","Siswa mengekspresikan diri melalui 3 kegiatan","Siswa mengekspresikan diri melalui 2 kegiatan","Siswa mengekspresikan diri melalui 1 kegiatan","Siswa tidak pernah mengekspresikan diri melalui kegiatan   "]'),
(39, 'Siswa memperoleh pengalaman mengapresiasikan karya seni dan budaya dalam 1 tahun terakhir.', '["Program keahlian memfasilitasi 4 atau lebih kegiatan","Program keahlian memfasilitasi 3 kegiatan","Program keahlian memfasilitasi 2 kegiatan","Program keahlian memfasilitasi 1 kegiatan","Program keahlian tidak pernah memfasilitasi kegiatan "]'),
(40, 'Siswa memperoleh pengalaman belajar melalui kegiatan yang mengembangkan sikap percaya diri dan tanggung jawab dalam 1 tahun terakhir.', '["Program keahlian menjalankan 4 atau lebih kegiatan","Program keahlian menjalankan 3 kegiatan","Program keahlian menjalankan 2 kegiatan","Program keahlian menjalankan 1 kegiatan","Program keahlian tidak pernah menjalankan kegiatan "]'),
(41, 'Siswa memperoleh pengalaman belajar untuk berpartisipasi dalam penegakan aturan-aturan sosial.', '["Program keahlian menjalankan kegiatan penegakan aturan-aturan sosial sebanyak 4 jenis dan/atau 4 kali atau lebih dalam 1 tahun terakhir","Program keahlian menjalankan kegiatan penegakan aturan-aturan sosial sebanyak 3 jenis dan/atau 3 kali dalam 1 tahun terakhir","Program keahlian menjalankan kegiatan penegakan aturan-aturan sosial sebanyak 2 jenis dan/atau 2 kali dalam 1 tahun terakhir","Program keahlian menjalankan kegiatan penegakan aturan-aturan sosial sebanyak 1 jenis dan/atau 1 kali dalam 1 tahun terakhir","Program keahlian tidak pernah menjalankan kegiatan penegakan aturan-aturan sosial   "]'),
(42, 'Siswa memperoleh pengalaman belajar yang mampu menumbuhkan sikap kompetitif dan sportif untuk mendapatkan hasil yang terbaik 3 tahun terakhir.', '["Sekolah/Madrasah melaksanakan 4 atau lebih kegiatan","Sekolah/Madrasah melaksanakan 3 kegiatan","Sekolah/Madrasah melaksanakan 2 kegiatan","Sekolah/Madrasah melaksanakan 1 kegiatan","Sekolah/Madrasah tidak melaksanakan kegiatan "]'),
(43, 'Siswa memperoleh pengalaman belajar yang dapat melibatkan partisipasi siswa dalam kehidupan bermasyarakat, berbangsa, dan bernegara secara demokratis dalam 3 tahun terakhir.', '["Program keahlian melaksanakan 4 kali atau lebih kegiatan","Program keahlian melaksanakan 3 kali kegiatan","Program keahlian melaksanakan 2 kali kegiatan","Program keahlian melaksanakan 1 kali kegiatan","Program keahlian tidak melaksanakan kegiatan "]'),
(44, 'Siswa memperoleh pengalaman belajar untuk membentuk karakter siswa, menumbuhkan rasa sportivitas, dan kebersihan lingkungan dalam 3 tahun terakhir.', '["Program keahlian melaksanakan 4 kali atau lebih kegiatan","Program keahlian melaksanakan 3 kali kegiatan","Program keahlian melaksanakan 2 kali kegiatan","Program keahlian melaksanakan 1 kali kegiatan","Program keahlian tidak melaksanakan kegiatan   "]'),
(45, 'Siswa memperoleh pengalaman belajar melalui pembiasaan untuk memahami hak dan kewajiban orang lain dalam pergaulan di masyarakat.', '["91%-100% silabus khususnya mata pelajaran Pendidikan Kewarganegaraan dan IPS memuat kegiatan pembelajaran dalam kemampuan memahami hak dan kewajiban orang lain dalam pergaulan di masyarakat","81%-90% silabus khususnya mata pelajaran Pendidikan Kewarganegaraan dan IPS memuat kegiatan pembelajaran dalam kemampuan memahami hak dan kewajiban orang lain dalam pergaulan di masyarakat","71%-80% silabus khususnya mata pelajaran Pendidikan Kewarganegaraan dan IPS memuat kegiatan pembelajaran dalam kemampuan memahami hak dan kewajiban orang lain dalam pergaulan di masyarakat","61%-70% silabus khususnya mata pelajaran Pendidikan Kewarganegaraan dan IPS memuat kegiatan pembelajaran dalam kemampuan memahami hak dan kewajiban orang lain dalam pergaulan di masyarakat","Kurang dari 61% silabus khususnya mata pelajaran Pendidikan Kewarganegaraan dan IPS memuat kegiatan pembelajaran dalam kemampuan memahami hak dan kewajiban orang lain dalam pergaulan di masyarakat "]'),
(46, 'Siswa memperoleh pengalaman belajar untuk dapat menjalankan ajaran agama melalui kelompok mata pelajaran agama dan akhlak mulia yang bersifat afektif dalam 3 tahun terakhir.', '["Program keahlian memfasilitasi 4 jenis atau lebih kegiatan pembiasaan dan pengamalan ajaran agama","Program keahlian memfasilitasi 3 jenis kegiatan pembiasaan dan pengamalan ajaran agama","Program keahlian memfasilitasi 2 jenis kegiatan pembiasaan dan pengamalan ajaran agama","Program keahlian memfasilitasi 1 jenis kegiatan pembiasaan dan pengamalan ajaran agama","Program keahlian tidak melaksanakan kegiatan pembiasaan dan pengamalan ajaran agama   "]'),
(47, 'Siswa mengikuti pembelajaran untuk memperoleh pengalaman menghargai keberagaman agama, bangsa, suku, ras, dan golongan sosial ekonomi dalam lingkup global dalam 3 tahun terakhir', '["Program keahlian melaksanakan 4 atau lebih kegiatan pembelajaran","Program keahlian melaksanakan 3 kegiatan pembelajaran","Program keahlian melaksanakan 2 kegiatan pembelajaran","Program keahlian melaksanakan 1 kegiatan pembelajaran","Program keahlian tidak melaksanakan kegiatan pembelajaran "]'),
(48, 'Siswa memperoleh pengalaman belajar dalam pembentukan akhlak mulia melalui berbagai jenis kegiatan pengembangan diri setiap bulan.', '["Program keahlian melaksanakan 4 atau lebih kegiatan pengembangan diri","Program keahlian melaksanakan 3 kegiatan pengembangan diri","Program keahlian melaksanakan 2 kegiatan pengembangan diri","Program keahlian melaksanakan 1 kegiatan pengembangan diri","Program keahlian tidak melaksanakan kegiatan pengembangan diri "]'),
(49, 'Siswa memperoleh pengalaman belajar untuk menghargai perbedaan pendapat dan berempati terhadap orang lain melalui mata pelajaran yang menggunakan pendekatan diskusi, kerja kelompok, dan persaingan sehat.', '["10 atau lebih mata pelajaran","8-9 mata pelajaran","6-7 mata pelajaran","4-5 mata pelajaran","Kurang dari 4 mata pelajaran   "]'),
(50, 'Siswa mengikuti kegiatan untuk memperoleh pengalaman belajar dalam menghasilkan karya kreatif baik individual maupun kelompok setiap tahun.', '["Program keahlian memfasilitasi 4 atau lebih kegiatan","Program keahlian memfasilitasi 3 kegiatan","Program keahlian memfasilitasi 2 kegiatan","Program keahlian memfasilitasi 1 kegiatan","Program keahlian tidak pernah memfasilitasi kegiatan "]'),
(51, 'Siswa mengikuti kegiatan yang memfasilitasi siswa dalam berkomunikasi baik lisan maupun tulisan secara efektif dan santun dalam 1 tahun terakhir.', '["Program keahlian memfasilitasi 4 atau lebih kegiatan","Program keahlian memfasilitasi 3 kegiatan","Program keahlian memfasilitasi 2 kegiatan","Program keahlian memfasilitasi 1 kegiatan","Program keahlian tidak memfasilitasi kegiatan "]'),
(52, 'Siswa memperoleh keterampilan membaca dan menulis naskah secara sistematis dan estetis, melalui: (1) karya tulis, (2) lomba, (3) kunjungan karya wisata/studi lapangan, (4) majalah dinding, (5) buletin siswa, dan kegiatan lain yang terkait.', '["Melalui 4 atau lebih kegiatan","Melalui 3 kegiatan","Melalui 2 kegiatan","Melalui 1 kegiatan","Tidak melakukan kegiatan "]'),
(53, 'Siswa mengikuti kegiatan untuk memperoleh keterampilan menyimak, membaca, menulis, dan berbicara, baik dalam Bahasa Indonesia maupun Bahasa Inggris setiap tahun.', '["Program keahlian memfasilitasi 4 atau lebih kegiatan","Program keahlian memfasilitasi 3 kegiatan","Program keahlian memfasilitasi 2 kegiatan","Program keahlian memfasilitasi 1 kegiatan","Program keahlian tidak memfasilitasi kegiatan   "]'),
(54, 'Siswa mengikuti kegiatan untuk memperoleh pengalaman belajar dalam mengembangkan ipteks (ilmu pengetahuan, teknologi, dan seni) seiring dengan perkembangannya setiap tahun.', '["Program keahlian memfasilitasi 4 atau lebih kegiatan","Program keahlian memfasilitasi 3 kegiatan","Program keahlian memfasilitasi 2 kegiatan","Program keahlian memfasilitasi 1 kegiatan","Program keahlian tidak memfasilitasi kegiatan "]'),
(55, 'Siswa mengikuti kegiatan untuk memperoleh pengalaman belajar agar menguasai atau memiliki kompetensi keahlian dan jiwa kewirausahaan, melalui pembelajaran berbasis masalah dan/atau pembelajaran berbasis proyek.', '["Melalui 4 atau lebih mata pelajaran","Melalui 3 mata pelajaran","Melalui 2 mata pelajaran","Melalui 1 mata pelajaran","Tidak melakukan "]'),
(56, 'Program keahlian memiliki prestasi yang ditunjukkan dengan pencapaian nilai rata-rata UN teori kelompok mata pelajaran produktif pada tahun terakhir.', '["Mencapai nilai rata-rata 2,00 atau lebih di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 1,01 sampai 1,99 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 0,01 sampai 1,00 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata sama dengan batas nilai kelulusan UN","Lebih rendah dari batas nilai kelulusan UN   "]'),
(57, 'Program keahlian memiliki prestasi yang ditunjukkan dengan pencapaian batas nilai kelulusan UN mata pelajaran Matematika pada tahun terakhir.', '["Mencapai nilai rata-rata 2,00 atau lebih di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 1,01 sampai 1,99 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 0,01 sampai 1,00 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata sama dengan batas nilai kelulusan UN","Lebih rendah dari batas nilai kelulusan UN "]'),
(58, 'Program keahlian memiliki prestasi yang ditunjukkan dengan pencapaian batas nilai kelulusan UN mata pelajaran Bahasa Inggris pada tahun terakhir.', '["Mencapai nilai rata-rata 2,00 atau lebih di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 1,01 sampai 1,99 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 0,01 sampai 1,00 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata sama dengan batas nilai kelulusan UN","Lebih rendah dari batas nilai kelulusan UN "]'),
(59, 'Program keahlian memiliki prestasi yang ditunjukkan dengan pencapaian batas nilai kelulusan UN mata pelajaran Bahasa Indonesia pada tahun terakhir.', '["Mencapai nilai rata-rata 2,00 atau lebih di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 1,01 sampai 1,99 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata 0,01 sampai 1,00 di atas batas nilai kelulusan UN","Mencapai nilai rata-rata sama dengan batas nilai kelulusan UN","Lebih rendah dari batas nilai kelulusan UN   "]'),
(60, 'Program keahlian memiliki prestasi yang ditunjukkan dengan pencapaian nilai rata-rata uji kompetensi mata pelajaran produktif pada tahun terakhir.', '["Nilai rata-rata 7,5 atau lebih","Nilai rata-rata 7,0 – 7,4","Nilai rata-rata 6,5 – 6,9","Nilai rata-rata 6,0 – 6,4","Nilai rata-rata lebih rendah dari 6,0 "]'),
(61, 'Program keahlian memiliki prestasi yang ditunjukkan dengan persentase tingkat kelulusan pada 3 tahun terakhir.', '["Kelulusan 100%","Kelulusan 96%-99%","Kelulusan 90%-95%","Kelulusan 86%-89%","Kelulusan kurang dari 86% "]'),
(62, 'Program keahlian memiliki lulusan yang bekerja di DU/DI yang sesuai dengan kompetensi keahliannya dalam 3 tahun terakhir', '["91%-100% telah bekerja di DU/DI yang sesuai kompetensi keahliannya","81%-90% telah bekerja di DU/DI yang sesuai kompetensi keahliannya","71%-80% telah bekerja di DU/DI yang sesuai kompetensi keahliannya","61%-70% telah bekerja di DU/DI yang sesuai kompetensi keahliannya","Tidak ada Lulusan yang bekerja sesuai kompetensi keahliannya   "]'),
(63, 'Guru memiliki kualifikasi akademik minimum sarjana (S1) atau diploma empat (D-IV). Untuk bidang tertentu, kualifikasi kepakaran ditunjukkan dengan pengakuan lain setingkat S1 atau D-IV.', '["96%-100% guru berpendidikan minimum S1 atau D-IV","91%-95% guru berpendidikan minimum S1 atau D-IV","86%-90% guru berpendidikan minimum S1 atau D-IV","81%-85% guru berpendidikan minimum S1 atau D-IV","Kurang dari 81% guru berpendidikan minimum S1 atau D-IV "]'),
(64, 'Guru mata pelajaran mengajar sesuai dengan latar belakang pendidikannya.', '["96%-100% guru mata pelajaran memiliki kesesuaian","91%-95% guru mata pelajaran memiliki kesesuaian","86%-90% guru mata pelajaran memiliki kesesuaian","81%-85% guru mata pelajaran memiliki kesesuaian","Kurang dari 81% guru mata pelajaran memiliki kesesuaian "]'),
(65, 'Program keahlian memiliki guru mata pelajaran produktif sesuai dengan program keahliannya.', '["96%-100% guru mata pelajaran produktif memiliki kesesuaian","91%-95% guru mata pelajaran produktif memiliki kesesuaian","86%-90% guru mata pelajaran produktif memiliki kesesuaian","81%-85% guru mata pelajaran produktif memiliki kesesuaian","Kurang dari 81% gurumata pelajaran produktif memiliki kesesuaian   "]'),
(66, 'Guru memiliki kesehatan jasmani dan rohani untuk menjalankan tugas utamanya..', '["Rata-rata kehadiran guru 96%-100% untuk menjalankan tugas utamanya","Rata-rata kehadiran guru 91%-95% untuk menjalankan tugas utamanya","Rata-rata kehadiran guru 86%-90% untuk menjalankan tugas utamanya","Rata-rata kehadiran guru 81%-85% untuk menjalankan tugas utamanya","Rata-rata kehadiran guru kurang dari 81% untuk menjalankan tugas utamanya "]'),
(67, 'Guru merencanakan, melaksanakan, dan mengevaluasi pembelajaran sesuai dengan prinsip-prinsip pembelajaran.', '["96%-100% guru merencanakan, melaksanakan, dan mengevaluasi pembelajaran sesuai dengan prinsip-prinsip pembelajaran","91%-95% guru merencanakan, melaksanakan, dan mengevaluasi pembelajaran sesuai dengan prinsip-prinsip pembelajaran","86%-90% guru merencanakan, melaksanakan, dan mengevaluasi pembelajaran sesuai dengan prinsip-prinsip pembelajaran","81%-85% guru merencanakan, melaksanakan, dan mengevaluasi pembelajaran sesuai dengan prinsip-prinsip pembelajaran","Kurang dari 81% guru merencanakan, melaksanakan, dan mengevaluasi pembelajaran sesuai dengan prinsip-prinsip pembelajaran "]'),
(68, 'Guru memiliki integritas kepribadian dan bertindak sesuai dengan norma agama, hukum, sosial, serta peraturan dan ketentuan yang berlaku.', '["Semua guru bertindak sesuai dengan norma agama, hukum, sosial, serta peraturan dan ketentuan yang berlaku","Terdapat guru yang diberi kesempatan memperbaiki diri dan dilakukan pembinaan","Adanya guru yang diberikan peringatan lisan","Adanya guru yang diberikan peringatan tertulis","Adanya guru yang dibebastugaskan dari mengajar atau dikeluarkan   "]'),
(69, 'Guru berkomunikasi secara efektif dan santun dengan sesama guru, tenaga kependidikan, siswa, dan orangtua siswa.', '["Guru berkomunikasi efektif dan santun dengan siswa, sesama guru, kepala sekolah/madrasah, orang tua siswa, dan komite sekolah/madrasah","Guru berkomunikasi efektif dan santun dengan siswa, sesama guru, kepala sekolah/madrasah, dan orang tua siswa","Guru berkomunikasi efektif dan santun dengan siswa, sesama guru, dan kepala sekolah/madrasah","Guru berkomunikasi efektif dan santun dengan siswa dan sesama guru","Guru tidak mampu berkomunikasi efektif dan santun "]'),
(70, 'Guru menguasai materi pelajaran yang diampu serta mengembangkannya secara ilmiah.', '["96%-100% guru memiliki kesesuaian sertifikat pendidik dengan mata pelajaran yang diampu, menghasilkan karya tulis, dan mengikuti berbagai pertemuan ilmiah","91%-95% guru memiliki kesesuaian sertifikat pendidik dengan mata pelajaran yang diampu, menghasilkan karya tulis, dan mengikuti berbagai pertemuan ilmiah","86%-90% guru memiliki sertifikat pendidik dengan mata pelajaran yang diampu, menghasilkan karya tulis, dan mengikuti berbagai pertemuan ilmiah","81%-85% guru memiliki sertifikat pendidik dengan mata pelajaran yang diampu, menghasilkan karya tulis, dan mengikuti berbagai pertemuan ilmiah","Kurang dari 81% guru memiliki sertifikat pendidik dengan mata pelajaran yang diampu, menghasilkan karya tulis, dan mengikuti berbagai pertemuan ilmiah   "]'),
(71, 'Guru mata pelajaran produktif memiliki sertifikat keahlian sesuai dengan mata pelajaran yang diampunya.', '["76%-100% guru mata pelajaran produktif memiliki sertifikat uji kompetensi dari Lembaga Sertifikasi Profesi (LSP) sesuai keahliannya","51%-75% guru mata pelajaran produktif memiliki sertifikat uji kompetensi dari Lembaga Sertifikasi Profesi (LSP) sesuai keahliannya","26%-50% guru mata pelajaran produktif memiliki sertifikat uji kompetensi dari Lembaga Sertifikasi Profesi (LSP) sesuai keahliannya","1%-25% guru mata pelajaran produktif memiliki sertifikat uji kompetensi dari Lembaga Sertifikasi Profesi (LSP) sesuai keahliannya","Tidak ada guru mata pelajaran produktif memiliki sertifikat uji kompetensi dari Lembaga Sertifikasi Profesi (LSP) "]'),
(72, 'Guru mata pelajaran produktif memiliki satu kompetensi utama dan dua kompetensi tambahan.', '["96%-100% atau lebih guru mata pelajaran produktif memiliki satu kompetensi utama dan dua kompetensi tambahan","91%-96% guru mata pelajaran produktif memiliki satu kompetensi utama dan dua kompetensi tambahan","86%-90% guru mata pelajaran produktif memiliki satu kompetensi utama dan dua kompetensi tambahan","81%-85% guru mata pelajaran produktif memiliki satu kompetensi utama dan dua kompetensi tambahan","Kurang dari 81% guru mata pelajaran produktif yang memiliki satu kompetensi utama dan dua kompetensi tambahan "]'),
(73, 'Ketua program keahlian berstatus sebagai guru, memiliki sertifikat pendidik, dan Surat Keputusan (SK) sebagai ketua program keahlian.', '["Berstatus sebagai guru, memiliki sertifikat pendidik, dan memiliki SK sebagai ketua program keahlian","Berstatus sebagai guru, tidak memiliki sertifikat pendidik, tetapi memiliki SK sebagai ketua program keahlian","Berstatus sebagai guru, memiliki sertifikat pendidik, tetapi tidak memiliki SK sebagai ketua program keahlian","Tidak berstatus sebagai guru, tidak memiliki sertifikat pendidik, tetapi memiliki SK sebagai ketua program keahlian","Tidak berstatus sebagai guru, tidak memiliki sertifikat pendidik, dan tidak memiliki SK sebagai ketua program keahlian   "]'),
(74, 'Ketua program keahlian memiliki kualifikasi akademik minimum sarjana (S1) atau diploma empat (D-IV), atau sertifikat keahlian yang setara', '["Memiliki kualifikasi akademik minimum S1 atau D-IV kependidikan dari perguruan tinggi terakreditasi","Memiliki kualifikasi akademik minimum S1 atau D-IV nonkependidikan dari perguruan tinggi terakreditasi","Memiliki kualifikasi akademik minimum S1 atau D-IV kependidikan dari perguruan tinggi tidak terakreditasi","Memiliki kualifikasi akademik minimum S1 atau D-IV nonkependidikan dari perguruan tinggi tidak terakreditasi","Tidak memiliki kualifikasi akademik minimum yang dipersyaratkan "]'),
(75, 'Ketua program keahlian memiliki pengalaman mengajar', '["Memiliki pengalaman mengajar 4 tahun atau lebih","Memiliki pengalaman mengajar 3 tahun","Memiliki pengalaman mengajar 2 tahun","Memiliki pengalaman mengajar 1 tahun","Tidak memiliki pengalaman mengajar "]'),
(76, 'Ketua program keahlian memiliki kemampuan manajerial yang ditunjukkan dengan keberhasilan mengelola program keahlian.', '["91%-100% lulusan yang sudah bekerja tetap dan diterima di perguruan tinggi terakreditasi pada dua tahun terakhir","81%-90% lulusan yang sudah bekerja tetap dan diterima di perguruan tinggi terakreditasi pada dua tahun terakhir","71%-80% lulusan yang sudah bekerja tetap dan diterima di perguruan tinggi terakreditasi pada dua tahun terakhir","61%-70% lulusan yang sudah bekerja tetap dan diterima di perguruan tinggi terakreditasi pada dua tahun terakhir","Kurang dari 61% lulusan yang sudah bekerja tetap dan diterima di perguruan tinggi terakreditasi pada dua tahun terakhir   "]'),
(77, 'Kepala sekolah/madrasah memiliki minat kewirausahaan yang ditunjukkan kemampuan mengelola kegiatan produksi/jasa sebagai sumber belajar siswa.', '["Mampu mengelola kegiatan unit usaha yang cukup untuk membiayai 76%-100% biaya kegiatan ekstrakurikuler secara mandiri","Mampu mengelola kegiatan unit usaha yang cukup untuk membiayai 51%-75% biaya kegiatan ekstrakurikuler secara mandiri","Mampu mengelola kegiatan unit usaha yang cukup untuk membiayai 26%-50% biaya kegiatan ekstrakurikuler secara mandiri","Mampu mengelola kegiatan unit usaha yang cukup untuk membiayai 1%-25% biaya kegiatan ekstrakurikuler secara mandiri","Tidak mampu mengelola unit usaha "]'),
(78, 'Kepala sekolah/madrasah melakukan supervisi setiap tahun.', '["91%-100% guru telah disupervisi","81%-90% guru telah disupervisi","71%-80% guru telah disupervisi","61%-70% guru telah disupervisi","Kurang dari 61% guru telah disupervisi "]'),
(79, 'Sekolah/Madrasah memiliki tenaga administrasi yang berpendidikan menengah atau yang sederajat.', '["5 orang atau lebih","4 orang","3 orang","2 orang","Kurang dari 2 orang   "]'),
(80, 'Tenaga administrasi memiliki latar belakang pendidikan yang sesuai dengan bidang tugasnya.', '["5 orang atau lebih tenaga administrasi yang memiliki kesesuaian","4 orang tenaga administrasi yang memiliki kesesuaian","3 orang tenaga administrasi yang memiliki kesesuaian","2 atau 1 orang tenaga administrasi yang memiliki kesesuaian","Tidak memiliki tenaga administrasi yang memiliki kesesuaian "]'),
(81, 'Sekolah/Madrasah memiliki kepala perpustakaan dengan kualifikasi minimal D2 ilmu perpustakaan dan memiliki sertifikat kompetensi pengelolaan perpustakaan sekolah/madrasah.', '["Memiliki kualifikasi minimal D2 ilmu perpustakaan dan memiliki sertifikat","Memiliki kualifikasi minimal D2 ilmu perpustakaan dan tidak memiliki sertifikat","Memiliki kualifikasi minimal D2 bukan ilmu perpustakaan dan memiliki sertifikat","Memiliki kualifikasi minimal D2 bukan ilmu perpustakaan dan tidak memiliki sertifikat","Tidak memiliki kepala perpustakaan "]'),
(82, 'Sekolah/Madrasah memiliki tenaga perpustakaan dengan kualifikasi minimal SMA atau yang sederajat dan memiliki sertifikat kompetensi pengelolaan perpustakaan sekolah/madrasah.', '["Memiliki kualifikasi minimal SMA atau yang sederajat dan memiliki sertifikat.","Memiliki kualifikasi minimal SMA atau yang sederajat dan tidak memiliki sertifikat","Memiliki kualifikasi di bawah SMA dan memiliki sertifikat","Memiliki kualifikasi di bawah SMA dan tidak memiliki sertifikat","Tidak memiliki tenaga perpustakaan   "]'),
(83, 'Program keahlian memiliki kepala laboratorium/bengkel dengan kualifikasi minimal D3 dan memiliki sertifikat kepala laboratorium sekolah/madrasah', '["Memiliki kualifikasi minimal D3 dan memiliki sertifikat.","Memiliki kualifikasi minimal D3 dan tidak memiliki sertifikat.","Memiliki kualifikasi di bawah D3 dan memiliki sertifikat.","Memiliki kualifikasi di bawah D3 dan tidak memiliki sertifikat.","Tidak memiliki kepala laboratorium/bengkel "]'),
(84, 'Program keahlian memiliki teknisi laboratorium/bengkel dengan kualifikasi minimal D2 dan memiliki sertifikat teknisi.', '["Memiliki kualifikasi minimal D2 yang relevan dan memiliki sertifikat.","Memiliki kualifikasi minimal D2 yang relevan dan tidak memiliki sertifikat","Memiliki kualifikasi minimal D2 yang tidak relevan dan memiliki sertifikat","Memiliki kualifikasi minimal D2 yang tidak relevan dan tidak memiliki sertifikat","Tidak memiliki teknisi laboratorium/bengkel "]'),
(85, 'Program keahlian memiliki laboran dengan kualifikasi akademik minimum sesuai standar tenaga laboratorium sesuai dengan ketentuan yang berlaku', '["Memiliki kualifikasi minimal D1 yang relevan dan memiliki sertifikat.","Memiliki kualifikasi minimal D1 yang relevan dan tidak memiliki sertifikat","Memiliki kualifikasi minimal D1 yang tidak relevan dan memiliki sertifikat","Memiliki kualifikasi minimal D1 yang tidak relevan dan tidak memiliki sertifikat","Tidak memiliki laboran   "]'),
(86, 'Program keahlian memiliki petugas layanan khusus.', '["Memiliki 4 jenis atau lebih petugas layanan khusus","Memiliki 3 jenis petugas layanan khusus","Memiliki 2 jenis petugas layanan khusus","Memiliki 1 jenis petugas layanan khusus","Tidak memiliki petugas layanan khusus "]'),
(87, 'Program keahlian memiliki tenaga teknisi perawatan (maintenance) peralatan dan gedung.', '["Program keahlian memiliki 1 tenaga teknisi untuk maintenance peralatan dan 1 tenaga teknisi untuk maintenance gedung","program keahlian memiliki 1 tenaga teknisi untuk maintenance peralatan dan gedung","Sekolah/Madrasah memiliki 1 tenaga teknisi maintenance peralatan dan 1 tenaga teknisi maintenance gedung","Sekolah/Madrasah memiliki 1 tenaga teknisi maintenance peralatan dan gedung","Tidak memiliki tenaga teknisi maintenance peralatan dan gedung   "]'),
(88, 'Sekolah/madrasah memiliki luas lahan sesuai ketentuan.', '["Memiliki luas lahan 91%-100% atau lebih dari ketentuan luas lahan minimal","Memiliki luas lahan 81%-90% dari ketentuan luas lahan minimal","Memiliki luas lahan 71%-80% dari ketentuan luas lahan minimal","Memiliki luas lahan 61%-70% dari ketentuan luas lahan minimal","Memiliki luas lahan kurang dari 61% dari ketentuan luas lahan minimal "]'),
(89, 'Sekolah/madrasah berada di lokasi yang (1) aman, (2) terhindar dari potensi bahaya yang mengancam kesehatan, (3) keselamatan jiwa, serta (4) memiliki akses untuk penyelamatan dalam keadaan darurat.', '["Memenuhi 4 syarat keamanan","Memenuhi 3 syarat keamanan","Memenuhi 2 syarat keamanan","Memenuhi 1 syarat keamanan","Tidak memenuhi syarat keamanan "]'),
(90, 'Sekolah/madrasah berada di lokasi yang nyaman, (1) terhindar dari gangguan pencemaran air, (2) kebisingan, (3) pencemaran udara, dan (4) memiliki sarana untuk meningkatkan kenyamanan.', '["Memenuhi 4 syarat kenyamanan","Memenuhi 3 syarat kenyamanan","Memenuhi 2 syarat kenyamanan","Memenuhi 1 syarat kenyamanan","Tidak memenuhi syarat kenyamanan   "]'),
(91, 'Fasilitas pembelajaran berada di lokasi yang sesuai dengan peruntukannya, memiliki status hak atas tanah, dan ijin pemanfaatan dari pemegang hak atas tanah.', '["Berada di lokasi yang sesuai dengan peruntukannya, memiliki status hak atas tanah dan ijin pemanfaatan dari pemegang hak atas tanah","Berada di lokasi yang sesuai dengan peruntukannya dan memiliki status hak atas tanah, tetapi tidak memiliki ijin pemanfaatan dari pemegang hak atas tanah","Berada di lokasi yang sesuai dengan peruntukannya, tetapi tidak memiliki status hak atas tanah dan tidak memiliki ijin pemanfaatan dari pemegang hak atas tanah","Tidak berada di lokasi yang sesuai dengan peruntukannya, tetapi memiliki status hak atas tanah dan memiliki ijin pemanfaatan dari pemegang hak atas tanah","Tidak berada di lokasi sesuai dengan peruntukannya "]'),
(92, 'Program keahlian memiliki lantai bangunan sesuai dengan ketentuan luas minimal', '["Memiliki luas lantai 91%-100% atau lebih dari ketentuan luas minimal","Memiliki luas lantai 81%-90% dari ketentuan luas minimal","Memiliki luas lantai 71%-80% dari ketentuan luas minimal","Memiliki luas l lantai 61%-70% dari ketentuan luas minimal","Memiliki luas lantai kurang dari 61% dari ketentuan luas minimal "]'),
(93, 'Bangunan sekolah/madrasah memiliki (1) struktur yang stabil dan kokoh serta dilengkapi dengan (2) sistem pencegahan bahaya kebakaran dan (3) penangkal petir.', '["Bangunan memiliki (1), (2), dan (3)","Bangunan memiliki (1) dan (2)","Bangunan memiliki (1) dan (3)","Bangunan memiliki (1)","Bangunan tidak memiliki (1), (2), dan (3)   "]'),
(94, 'Sekolah/madrasah memiliki sanitasi di dalam dan di luar bangunan yang dapat memenuhi kebutuhan: (1) air bersih, (2) saluran air kotor dan/atau air limbah, (3) tempat sampah, dan (4) saluran air hujan.', '["Memiliki sanitasi di dalam dan di luar bangunan yang memenuhi (1), (2), (3), dan (4).","Memiliki sanitasi di dalam dan di luar bangunan yang memenuhi 3 dari 4 kebutuhan","Memiliki sanitasi di dalam dan di luar bangunan yang memenuhi 2 dari 4 kebutuhan","Memiliki sanitasi di dalam dan di luar bangunan yang memenuhi 1 dari 4 kebutuhan","Tidak memiliki sanitasi di dalam dan di luar yang memenuhi keempat kebutuhan di atas "]'),
(95, 'Sekolah/madrasah memiliki buku teks pelajaran dengan perbandingan (rasio).', '["1 buku teks/mata pelajaran/siswa","1 buku teks/mata pelajaran untuk 2-5 siswa","1 buku teks/mata pelajaran untuk 6-10 siswa","1 buku teks/mata pelajaran untuk 11 siswa atau lebih","Tidak memiliki buku teks "]'),
(96, 'Program keahlian memiliki mata pelajaran yang memanfaatkan buku teks sesuai dengan ketentuan yang berlaku', '["10 atau lebih mata pelajaran","8-9 mata pelajaran","6-7 mata pelajaran","4-5 mata pelajaran","Kurang dari 4 mata pelajaran   "]'),
(97, 'Bangunan sekolah/madrasah memiliki ventilasi udara dan pencahayaan yang memadai.', '["Memiliki ventilasi udara dan pencahayaan memadai","Memiliki ventilasi udara memadai tetapi pencahayaan yang kurang memadai","Memiliki ventilasi udara kurang memadai tetapi pencahayaan memadai","Memiliki ventilasi udara dan pencahayaan kurang memadai","Tidak memiliki ventilasi udara dan pencahayaan "]'),
(98, 'Bangunan sekolah/madrasah memiliki instalasi listrik dengan daya minimum 2200 Watt untuk administrasi sekolah dan ruang teori, serta daya tambahan untuk laboratorium dan bengkel sesuai kebutuhan.', '["Memiliki instalasi listrik dengan keterkecukupan daya sesuai kebutuhan","Memiliki instalasi listrik dengan keterkecukupan daya 90%-99% dari kebutuhan","Memiliki instalasi listrik dengan keterkecukupan daya 80%-89% dari kebutuhan","Memiliki instalasi listrik dengan keterkecukupan daya 70%-79% dari kebutuhan","Memiliki instalasi listrik dengan keterkecukupan daya kurang dari 70% kebutuhan "]'),
(99, 'Sekolah/Madrasah memiliki izin mendirikan bangunan dan izin penggunaan bangunan sesuai dengan peruntukannya.', '["Memiliki izin mendirikan bangunan dan izin penggunaan bangunan sesuai dengan peruntukannya sebelum bangunan berdiri","Memiliki izin mendirikan bangunan, dan memiliki izin penggunaan bangunan sesuai dengan peruntukannya setelah bangunan berdiri","Memiliki izin mendirikan dan memiliki izin penggunaan bangunan sementara","Memiliki izin mendirikan tetapi tidak memiliki izin penggunaan bangunan","Tidak memiliki izin mendirikan bangunan dan izin penggunaan bangunan   "]');
INSERT INTO `pertanyaan` (`id`, `pertanyaan`, `pilihan`) VALUES
(100, 'Sekolah/Madrasah melakukan pemeliharaan terhadap bangunan secara berkala.', '["Melakukan pemeliharaan ringan dan berat terhadap bangunan secara berkala sesuai ketentuan","Melakukan pemeliharaan ringan dan berat terhadap bangunan, tetapi melebihi waktu yang sesuai ketentuan","Melakukan pemeliharaan ringan tetapi melebihi waktu yang sesuai ketentuan, dan tidak pernah melakukan pemeliharaan berat","Melakukan pemeliharaan terhadap bangunan, jika sudah ada bagian bangunan yang rusak berat","Tidak pernah melakukan pemeliharaan "]'),
(101, 'Program keahlian memiliki ruang pembelajaran umum (RPU) sesuai dengan Standar Sarana dan Prasarana SMK/MAK.', '["Memiliki seluruh jenis RPU yang dipersyaratkan oleh setiap program keahlian","Memiliki ruang kelas, perpustakaan, lab bahasa, lab komputer, dan satu RPU yang lain","Memiliki ruang kelas, perpustakaan, lab komputer, dan lab bahasa","Memiliki ruang kelas, perpustakaan, dan lab komputer","Tidak memiliki RPU "]'),
(102, 'Program keahlian memiliki Ruang Pembelajaran Umum (RPU) dengan ukuran minimum sesuai dengan yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.', '["Memiliki 91%-100% RPU sesuai dengan yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.","Memiliki 81%-90% RPU dari yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.","Memiliki 71%-80% RPU dari yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.","Memiliki 61%-70% RPU dari yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.","Memiliki RPU kurang dari 60% dari yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.   "]'),
(103, 'Program keahlian memiliki Ruang Pembelajaran Umum (RPU) dengan sarana sebagaimana tercantum pada Standar Sarana dan Prasarana SMK/MAK.', '["91%-100% RPU mempunyai kelengkapan sarana sesuai dengan persyaratan dalam standar Sarana dan Prasarana SMK/MAK","81%-90% RPU mempunyai kelengkapan sarana sesuai dengan persyaratan dalam standar Sarana dan Prasarana SMK/MAK","71%-80% RPU mempunyai kelengkapan sarana sesuai dengan persyaratan dalam standar Sarana dan Prasarana SMK/MAK","61%-70% RPU mempunyai kelengkapan sarana sesuai dengan persyaratan dalam standar Sarana dan Prasarana SMK/MAK","Kurang dari 60% RPU sesuai dengan persyaratan dalam standar Sarana dan Prasarana SMK/MAK "]'),
(104, 'Sekolah/Madrasah memiliki ruang penunjang (RP) sesuai dengan Standar Sarana dan Prasarana SMK/MAK.', '["Memiliki 91%-100% RP sesuai dengan persyaratan dalam standar","Memiliki 81%-90% RP sesuai dengan persyaratan dalam standar","Memiliki 71%-80% RP sesuai dengan persyaratan dalam standar","Memiliki 61%-70% RP sesuai dengan persyaratan dalam standar","Memiliki kurang dari 60% RP sesuai dengan persyaratan dalam standar "]'),
(105, 'Sekolah/Madrasah memiliki RP dengan ukuran minimum sesuai dengan yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.', '["91%-100% RP memenuhi ukuran minimum sesuai dengan persyaratan dalam standar","81%-90% RP memenuhi ukuran minimum sesuai dengan persyaratan dalam standar","71%-80% RP memenuhi ukuran minimum sesuai dengan persyaratan dalam standar","61%-70% RP memenuhi ukuran minimum sesuai dengan persyaratan dalam standar","Kurang dari 60% RP memenuhi ukuran minimum sesuai dengan persyaratan dalam standar   "]'),
(106, 'Sekolah/Madrasah memiliki RP dengan sarana sebagaimana tercantum pada Standar Sarana dan Prasarana SMK/MAK.', '["91%-100% RP mempunyai kelengkapan sarana sesuai dengan persyaratan","81%-90% RP mempunyai kelengkapan sarana sesuai dengan persyaratan","71%-80% RP mempunyai kelengkapan sarana sesuai dengan persyaratan","Kurang dari 70% RP mempunyai kelengkapan sarana sesuai dengan persyaratan","Tidak ada satu pun RP mempunyai kelengkapan sarana sesuai dengan persyaratan "]'),
(107, 'Program keahlian memiliki ruang pembelajaran khusus (RPK) sesuai dengan Standar Sarana dan Prasarana SMK/MAK.', '["Memiliki 91%-100% RPK sesuai dengan persyaratan dalam standar","Memiliki 81%-90% RPK sesuai dengan persyaratan dalam standar","Memiliki 71%-80% RPK sesuai dengan persyaratan dalam standar","Memiliki 61%-70% RPK sesuai dengan persyaratan dalam standar","Memiliki kurang dari 61% RPK sesuai dengan persyaratan dalam standar "]'),
(108, 'Program keahlian memiliki RPK dengan ukuran minimum sesuai dengan yang disyaratkan pada Standar Sarana dan Prasarana SMK/MAK.', '["91%-100% RPK memenuhi ukuran minimum","81%-90% RPK memenuhi ukuran minimum","71%-80% RPK memenuhi ukuran minimum","61%-70% RPK memenuhi ukuran minimum","Kurang dari 61% RPK memenuhi ukuran minimum   "]'),
(109, 'Program keahlian memiliki RPK dengan sarana sebagaimana tercantum pada Standar Sarana dan Prasarana SMK/MAK.', '["91%-100% RPK sesuai dengan persyaratan dalam standar","81%-90% RPK sesuai dengan persyaratan dalam standar","71%-80% RPK sesuai dengan persyaratan dalam standar","61%-70% RPK sesuai dengan persyaratan dalam standar","Kurang dari 61% RPK sesuai dengan persyaratan dalam standar "]'),
(110, 'Sekolah/Madrasah memiliki unit produksi/business center sebagai wahana kewirausahaan, yang memiliki: (1) fasilitas usaha sendiri, (2) sistem usaha sendiri, (3) SDM yang melayani, dan (4) menghasilkan profit', '["Memenuhi 4 unsur","Memenuhi 3 unsur","Memenuhi 2 unsur","Memenuhi 1 unsur","Tidak memiliki unit produksi/business center "]'),
(111, 'Sekolah/Madrasah memiliki unit produksi/business center yang pasar usahanya tersebar luas.', '["Tersebar secara nasional.","Tersebar di beberapa kabupaten/kota atau provinsi","Tersebar di kabupaten/kota","Tersebar dalam lingkungan sekolah/madrasah","Tidak memiliki unit produksi/business center "]'),
(112, 'Sekolah/Madrasah memiliki Bursa Kerja Khusus (BKK) dengan berbagai kegiatan: (1) kerjasama dengan DU/DI, (2) memasarkan lulusan, (3) melakukan seleksi, dan (4) penyaluran lulusannya ke dunia kerja yang relevan', '["memiliki 4 kegiatan","memiliki 3 kegiatan","memiliki 2 kegiatan","memiliki 1 kegiatan","Tidak memiliki kegiatan   "]'),
(113, 'Sekolah/Madrasah telah merumuskan, menetapkan, dan mensosialisasikan visi lembaga.', '["Merumuskan dan menetapkan visi, mudah dipahami dan sering disosialisasikan","Merumuskan dan menetapkan visi, mudah dipahami dan pernah disosialisasikan","Merumuskan dan menetapkan visi, mudah dipahami tetapi tidak disosialisasikan","Merumuskan dan menetapkan visi, sulit dipahami dan tidak disosialisasikan","Tidak merumuskan dan menetapkan visi "]'),
(114, 'Sekolah/Madrasah telah merumuskan dan menetapkan misi lembaga.', '["Merumuskan dan menetapkan misi, mudah dipahami dan sering disosialisasikan","Merumuskan dan menetapkan misi, mudah dipahami dan pernah disosialisasikan","Merumuskan dan menetapkan misi, mudah dipahami tetapi tidak disosialisasikan","Merumuskan dan menetapkan misi, sulit dipahami dan tidak disosialisasikan","Tidak merumuskan dan menetapkan misi "]'),
(115, 'Program keahlian telah merumuskan dan menetapkan tujuan.', '["Merumuskan dan menetapkan tujuan, mudah dipahami dan sering disosialisasikan","Merumuskan dan menetapkan tujuan, mudah dipahami dan pernah disosialisasikan","Merumuskan dan menetapkan tujuan, mudah dipahami tetapi tidak disosialisasikan","Merumuskan dan menetapkan tujuan, sulit dipahami dan tidak disosialisasikan","Tidak merumuskan dan menetapkan tujuan   "]'),
(116, 'Program keahlian memiliki rencana kerja jangka menengah (empat tahunan) dan rencana kerja tahunan.', '["Memiliki rencana kerja jangka menengah dan rencana kerja tahunan dan sudah disosialisasikan","Memiliki rencana kerja jangka menengah dan rencana kerja tahunan serta salah satu yang sudah disosialisasikan","Memiliki rencana kerja jangka menengah dan rencana kerja tahunan serta belum disosialisasikan","Memiliki rencana kerja jangka menengah atau rencana kerja tahunan baik sudah maupun belum disosialisasikan","Tidak memiliki rencana kerja jangka menengah dan rencana kerja tahunan "]'),
(117, 'Program keahlian memiliki pedoman yang mengatur berbagai aspek pengelolaan secara tertulis yang mudah dipahami oleh pihak-pihak terkait.', '["Memiliki 7 atau lebih dokumen aspek pengelolaan secara tertulis","Memiliki 5-6 dokumen aspek pengelolaan secara tertulis","Memiliki 3-4 dokumen aspek pengelolaan secara tertulis","Memiliki 1-2 dokumen aspek pengelolaan secara tertulis","Tidak memiliki dokumen aspek pengelolaan secara tertulis "]'),
(118, 'Program keahlian memiliki struktur organisasi dengan kejelasan uraian tugas dan mekanisme kerja.', '["Memiliki struktur organisasi yang dipajang di dinding dan disertai uraian tugas yang jelas","Memiliki struktur organisasi dan disertai uraian tugas yang jelas","Memiliki struktur organisasi dan disertai uraian tugas tetapi tidak jelas","Memiliki struktur organisasi tetapi tidak ada uraian tugas.","Tidak memiliki struktur organisasi   "]'),
(119, 'Program keahlian melaksanakan kegiatan sesuai dengan rencana kerja tahunan.', '["91%-100% kegiatan dilaksanakan sesuai rencana kerja tahunan","81%-90% kegiatan dilaksanakan sesuai rencana kerja tahunan","71%-80% kegiatan dilaksanakan sesuai rencana kerja tahunan","61%-70% kegiatan dilaksanakan sesuai rencana kerja tahunan","Kurang dari 61% kegiatan dilaksanakan sesuai rencana kerja tahunan "]'),
(120, 'Program keahlian melaksanakan kegiatan kesiswaan.', '["Memiliki 4 atau lebih jenis kegiatan kesiswaan","Memiliki 3 jenis kegiatan kesiswaan","Memiliki 2 jenis kegiatan kesiswaan","Memiliki 1 jenis kegiatan kesiswaan","Tidak melaksanakan kegiatan kesiswaan "]'),
(121, 'Program keahlian melaksanakan kegiatan pengembangan kurikulum dan pembelajaran, meliputi: (1) KTSP, (2) Kalender pendidikan, (3) Program pembelajaran, (4) Penilaian hasil belajar siswa, dan (5) Peraturan akademik', '["Melaksanakan 4 atau lebih kegiatan","Melaksanakan 3 kegiatan","Melaksanakan 2 kegiatan","Melaksanakan 1 kegiatan","Tidak melaksanakan kegiatan   "]'),
(122, 'Sekolah/madrasah melaksanakan program pendayagunaan pendidik dan tenaga kependidikan, meliputi: (1) Pembagian tugas, (2) Penentuan sistem penghargaan, (3) Pengembangan profesi, (4) Promosi dan penempatan, dan (5) Mutasi', '["Melaksanakan 4 atau lebih program pendayagunaan pendidik dan tenaga kependidikan","Melaksanakan 3 program pendayagunaan pendidik dan tenaga kependidikan","Melaksanakan 2 program pendayagunaan pendidik dan tenaga kependidikan","Melaksanakan 1 program pendayagunaan pendidik dan tenaga kependidikan","Tidak melaksanakan program pendayagunaan pendidik dan tenaga kependidikan "]'),
(123, 'Program keahlian mengelola sarana dan prasarana pembelajaran.', '["Mengelola 4 atau lebih program sarana dan prasarana","Mengelola 3 program sarana dan prasarana","Mengelola 2 program sarana dan prasarana","Mengelola 1 program sarana dan prasarana","Tidak mengelola program sarana dan prasarana "]'),
(124, 'Sekolah/Madrasah mengelola pembiayaan pendidikan.', '["Memiliki 4 program pengelolaan pembiayaan pendidikan","Memiliki 3 program pengelolaan pembiayaan pendidikan","Memiliki 2 program pengelolaan pembiayaan pendidikan","Memiliki 1 program pengelolaan pembiayaan pendidikan","Tidak memiliki program pengelolaan pembiayaan pendidikan   "]'),
(125, 'Sekolah/Madrasah melaksanakan kegiatan untuk menciptakan suasana, iklim, dan lingkungan pembelajaran yang kondusif.', '["Melaksanakan 4 atau lebih kegiatan","Melaksanakan 3 kegiatan","Melaksanakan 2 kegiatan","Melaksanakan 1 kegiatan","Tidak melaksanakan kegiatan "]'),
(126, 'Sekolah/Madrasah memiliki kegiatan yang melibatkan masyarakat dan membangun kemitraan dengan lembaga lain yang relevan dalam pengelolaan pendidikan satu tahun terakhir.', '["Memiliki 4 atau lebih kegiatan","Memiliki 3 kegiatan","Memiliki 2 kegiatan","Memiliki 1 kegiatan","Tidak memiliki kegiatan "]'),
(127, 'Program keahlian melakukan kegiatan pelatihan kejuruan bagi teknisi atau laboran dalam rangka pemutakhiran keahlian kejuruan.', '["76%-100% teknisi atau laboran mengikuti pelatihan kejuruan","51%-75% teknisi atau laboran mengikuti pelatihan kejuruan","26%-50% teknisi atau laboran mengikuti pelatihan kejuruan","1%-25% teknisi atau laboran mengikuti pelatihan kejuruan","Tidak satu pun teknisi atau laboran mengikuti pelatihan kejuruan "]'),
(128, 'Sekolah/madrasah menjalin kerjasama dengan DU/DI dalam melaksanakan magang guru.', '["Memiliki 7 atau lebih kerjasama dengan DU/DI","Memiliki 5-6 kerjasama dengan DU/DI","Memiliki 3-4 kerjasama dengan DU/DI","Memiliki 1-2 kerjasama dengan DU/DI","Tidak memiliki kerjasama dengan DU/DI   "]'),
(129, 'Program keahlian menerapkan sistem manajemen mutu.', '["Program keahlian telah menerapkan dan memperoleh pengakuan sistem manajemen mutu pada pelayanan manajemen dan pembelajaran","Program keahlian telah menerapkan dan memperoleh pengakuan sistem manajemen mutu salah satu dari pelayanan manajemen atau pembelajaran","Program keahlian telah menerapkan sistem manajemen mutu, tetapi belum memperoleh pengakuan dari lembaga yang berwenang","Program keahlian sedang dalam tahap persiapan menuju sistem manajemen mutu pada kurun waktu 3 tahun mendatang","Program keahlian tidak memiliki program sistem manajemen mutu "]'),
(130, 'Program keahlian memiliki unit produksi/busines center yang bidang usahanya sesuai dengan kompetensi keahlian yang dimiliki.', '["Memiliki 4 jenis atau lebih barang atau jasa sesuai dengan kompetensi keahlian","Memiliki 3 jenis barang atau jasa sesuai dengan kompetensi keahlian","Memiliki 2 jenis barang atau jasa sesuai dengan kompetensi keahlian","Memiliki 1 jenis barang atau jasa sesuai dengan kompetensi keahlian","Tidak memiliki barang atau jasa sesuai dengan kompetensi keahlian "]'),
(131, 'Pengelolaan unit produksi/busines center melibatkan seluruh warga sekolah/madrasah.', '["Melibatkan guru, siswa, dan karyawan","Melibatkan guru dan siswa","Melibatkan siswa dan karyawan","Hanya melibatkan guru atau siswa atau karyawan saja","Tidak melibatkan semuanya   "]'),
(132, 'Bursa Kerja Khusus (BKK) yang dimiliki sekolah/madrasah mampu menyalurkan penempataan kerja bagi lulusan di DU/DI dalam 3 tahun terakhir.', '["Lebih dari 60% lulusan yang bekerja tercatat oleh BKK","46%-60% lulusan yang bekerja tercatat oleh BKK","31%-45% lulusan yang bekerja tercatat oleh BKK","16%-30% lulusan yang bekerja tercatat oleh BKK","Kurang dari 16% lulusan yang bekerja tercatat oleh BKK "]'),
(133, 'Sekolah/madrasah memiliki program pengawasan yang meliputi: (1) pemantauan, (2) supervisi, (3) evaluasi, (4) pelaporan, dan (5) tindak lanjut.', '["Memiliki 4 atau lebih program pengawasan","Memiliki 3 program pengawasan","Memiliki 2 program pengawasan","Memiliki 1 program pengawasan","Tidak memiliki program pengawasan "]'),
(134, 'Sekolah/madrasah melaksanakan kegiatan evaluasi diri.', '["Melaksanakan setiap tahun","Melaksanakan setiap 2 tahun","Melaksanakan setiap 3 tahun","Melaksanakan setiap 4 tahun","Tidak melaksanakan sama sekali   "]'),
(135, 'Sekolah/madrasah melaksanakan evaluasi kinerja pendidik dan tenaga kependidikan, meliputi: (1) kesesuaian penugasan dengan keahlian; (2) keseimbangan beban kerja; (3) kinerja pendidik dan tenaga kependidikan dalam pelaksanaan tugas; dan (4) pencapaian prestasi pendidik dan tenaga kependidikan.', '["Melaksanakan 4 atau lebih program","Melaksanakan 3 program","Melaksanakan 2 program","Melaksanakan 1 program","Tidak melakukan program "]'),
(136, 'Program keahlian mempersiapkan unsur-unsur pelaksanaan akreditasi yang meliputi: (1) dokumen yang diperlukan untuk mendukung akreditasi; (2) petugas yang akan mendampingi asesor; (3) bukti fisik nondokumen; dan (4) sarana dan prasarana pendukung pelaksanaan akreditasi.', '["Mempersiapkan 4 unsur pelaksanaan akreditasi","Mempersiapkan 3 unsur pelaksanaan akreditasi","Mempersiapkan 2 unsur pelaksanaan akreditasi","Mempersiapkan 1 unsur pelaksanaan akreditasi","Tidak mempersiapkan unsur pelaksanaan akreditasi. "]'),
(137, 'Sekolah/madrasah memiliki struktur kepemimpinan sesuai standar pendidik dan tenaga kependidikan.', '["Memiliki kepala sekolah/madrasah dan 4 atau lebih wakil kepala sekolah/madrasah","Memiliki kepala sekolah/madrasah dan 3 wakil kepala sekolah/madrasah","Memiliki kepala sekolah/madrasah dan 2 wakil kepala sekolah/madrasah","Memiliki kepala sekolah/madrasah dan 1 wakil kepala sekolah/madrasah","Memiliki kepala sekolah/madrasah dan tidak memiliki wakil kepala sekolah/madrasah   "]'),
(138, 'Sekolah/madrasah memiliki 4 komponen sistem informasi manajemen, yang meliputi: (1) Fasilitas sistem informasi yang efesien, efektif dan mudah diakses, (2) Sistem informasi untuk mendukung administrasi pendidikan, (3) Sistem kegiatan untuk melayani informasi/pengaduan dari luar, (4) Media komunikasi antarwarga sekolah/madrasah', '["memiliki 4 komponen","memiliki 3 komponen","memiliki 2 komponen","memiliki 1 komponen","Tidak memiliki komponen   "]'),
(139, 'Sekolah/madrasah memiliki dokumen investasi sarana dan prasarana.', '["Memiliki dokumen investasi sarana dan prasarana yang lengkap lebih dari 3 tahun terakhir","Memiliki dokumen investasi sarana dan prasarana yang lengkap selama 3 tahun terakhir","Memiliki dokumen investasi sarana dan prasarana yang lengkap selama 2 tahun terakhir","Memiliki dokumen investasi sarana dan prasarana yang lengkap selama 1 tahun terakhir","Tidak memiliki dokumen investasi sarana dan prasarana "]'),
(140, 'Sekolah/madrasah membelanjakan biaya untuk pengembangan pendidik dan tenaga kependidikan berdasarkan Rencana Kerja dan Anggaran Sekolah/Madrasah (RKA-S/M).', '["96%-100% dari anggaran pengembangan pendidik dan tenaga kependidikan dalam RKA-S/M","91%-95% dari anggaran pengembangan pendidik dan tenaga kependidikan dalam RKA-S/M","86%-90% dari anggaran pengembangan pendidik dan tenaga kependidikan dalam RKA-S/M","81%-85% dari anggaran pengembangan pendidik dan tenaga kependidikan dalam RKA-S/M","Kurang dari 81% dari anggaran pengembangan pendidik dan tenaga kependidikan dalam RKA-S/M "]'),
(141, 'Sekolah/madrasah merealisasikan modal kerja sesuai dengan RKA-S/M.', '["96%-100% modal kerja","91%-95% modal kerja","86%-90% modal kerja","81%-85% modal kerja","Kurang dari 81% modal kerja   "]'),
(142, 'Sekolah/madrasah membayar: (1) gaji, (2) honor kegiatan, (3) insentif, dan (4) tunjangan lain bagi guru.', '["Mengeluarkan dana untuk 4 jenis pengeluaran.","Mengeluarkan dana untuk 3 jenis pengeluaran.","Mengeluarkan dana untuk 2 jenis pengeluaran.","Mengeluarkan dana untuk 1 jenis pengeluaran.","Tidak mengeluarkan dana untuk 4 jenis pengeluaran. "]'),
(143, 'Sekolah/Madrasah membayar: (1) gaji, (2) honor kegiatan sekolah/madrasah, (3) insentif, dan (4) tunjangan lain bagi tenaga kependidikan pada tahun berjalan.', '["Mengeluarkan dana untuk 4 jenis pengeluaran.","Mengeluarkan dana untuk 3 jenis pengeluaran.","Mengeluarkan dana untuk 2 jenis pengeluaran.","Mengeluarkan dana untuk 1 jenis pengeluaran.","Tidak mengeluarkan dana untuk 4 jenis pengeluaran. "]'),
(144, 'Program keahlian membelanjakan biaya penunjang pelaksanaan kegiatan pembelajaran selama tiga tahun terakhir.', '["Membelanjakan 96%-100% biaya penunjang","Membelanjakan 91%-95% biaya penunjang","Membelanjakan 86%-90% biaya penunjang","Membelanjakan 81%-85% biaya penunjang","Membelanjakan kurang dari 81% biaya penunjang "]'),
(145, 'Sekolah/madrasah membelanjakan dana untuk kegiatan kesiswaan selama 1 tahun terakhir.', '["Membelanjakan 96%-100% anggaran","Membelanjakan 91%-95% anggaran","Membelanjakan 86%-90% anggaran","Membelanjakan 81%-85% anggaran","Membelanjakan kurang dari 81% anggaran   "]'),
(146, 'Program keahlian membelanjakan biaya pengadaan alat tulis untuk kegiatan pembelajaran selama 1 tahun terakhir.', '["Membelanjakan 96%-100% dari alokasi anggaran","Membelanjakan 91%-95% dari alokasi anggaran","Membelanjakan 86%-90% dari alokasi anggaran","Membelanjakan 81%-85% dari alokasi anggaran","Membelanjakan kurang dari 81% dari alokasi anggaran "]'),
(147, 'Sekolah/madrasah membelanjakan biaya pengadaan bahan habis pakai untuk kegiatan pembelajaran selama 1 tahun terakhir.', '["Membelanjakan 96%-100% alokasi anggaran","Membelanjakan 91%-95% alokasi anggaran","Membelanjakan 86%-90% alokasi anggaran","Membelanjakan 81%-85% alokasi anggaran","Membelanjakan kurang dari 81% alokasi anggaran "]'),
(148, 'Sekolah/madrasah membelanjakan biaya pengadaan alat habis pakai untuk kegiatan pembelajaran selama 1 tahun terakhir.', '["Membelanjakan 96%-100% alokasi anggaran","Membelanjakan 91%-95% alokasi anggaran","Membelanjakan 86%-90% alokasi anggaran","Membelanjakan 81%-85% alokasi anggaran","Membelanjakan kurang dari 81% alokasi anggaran "]'),
(149, 'Sekolah/madrasah membelanjakan biaya untuk kegiatan rapat selama 1 tahun terakhir.', '["Membelanjakan 96%-100% alokasi anggaran","Membelanjakan 91%-95% alokasi anggaran","Membelanjakan 86%-90% alokasi anggaran","Membelanjakan 81%-85% alokasi anggaran","Membelanjakan kurang dari 81% alokasi anggaran   "]'),
(150, 'Sekolah/madrasah membelanjakan biaya transportasi dan perjalanan dinas selama 1 tahun terakhir.', '["Membelanjakan 96%-100% alokasi anggaran","Membelanjakan 91%-95% alokasi anggaran","Membelanjakan 86%-90% alokasi anggaran","Membelanjakan 81%-85% alokasi anggaran","Membelanjakan kurang dari 81% alokasi anggaran "]'),
(151, 'Sekolah/madrasah membelanjakan biaya penggandaan soal-soal ulangan/ujian selama 1 tahun terakhir.', '["Membelanjakan 96%-100% alokasi anggaran","Membelanjakan 91%-95% alokasi anggaran","Membelanjakan 86%-90% alokasi anggaran","Membelanjakan 81%-85% alokasi anggaran","Membelanjakan kurang dari 81% alokasi anggaran "]'),
(152, 'Sekolah/madrasah membelanjakan biaya daya dan jasa selama 1 tahun terakhir.', '["Membelanjakan 96%-100% alokasi anggaran","Membelanjakan 91%-95% alokasi anggaran","Membelanjakan 86%-90% alokasi anggaran","Membelanjakan 81%-85% alokasi anggaran","Membelanjakan kurang dari 81% alokasi anggaran "]'),
(153, 'Sekolah/madrasah membelanjakan anggaran untuk mendukung kegiatan operasional tidak langsung selama 3 tahun terakhir.', '["Membelanjakan 96%-100% alokasi anggaran","Membelanjakan 91%-95% alokasi anggaran","Membelanjakan 86%-90% alokasi anggaran","Membelanjakan 81%-85% alokasi anggaran","Membelanjakan kurang dari 81% alokasi anggaran   "]'),
(154, 'Sekolah/madrasah membelanjakan biaya untuk menunjang kegiatan (1) prakerin, (2) uji kompetensi, (3) bimbingan karir, dan (4) program kewirausahaan.', '["Membelanjakan biaya untuk 4 kegiatan","Membelanjakan biaya untuk 3 kegiatan","Membelanjakan biaya untuk 2 kegiatan","Membelanjakan biaya untuk 1 kegiatan","Tidak membelanjakan "]'),
(155, 'Sumbangan pendidikan dari masyarakat dikelola secara baik dan dilaporkan kepada pihak: (1) orangtua siswa, (2) masyarakat, dan (3) dinas atau yayasan.', '["Dikelola secara baik dan dilaporkan kepada 3 pihak.","Dikelola secara baik dan dilaporkan kepada 2 pihak.","Dikelola secara baik dan dilaporkan kepada 1 pihak.","Dikelola secara baik tetapi tidak dilaporkan.","Dikelola dengan tidak baik dan tidak dilaporkan. "]'),
(156, 'Penetapan besarnya uang sekolah/madrasah atau program keahlian mempertimbangkan kemampuan ekonomi orangtua siswa.', '["91%-100% siswa dari keluarga tidak mampu mendapatkan keringanan","81%-90% siswa dari keluarga tidak mampu mendapatkan keringanan","71%-80% siswa dari keluarga tidak mampu mendapatkan keringanan","61%-70% siswa dari keluarga tidak mampu mendapatkan keringanan","Kurang dari 61% siswa dari keluarga tidak mampu mendapatkan keringanan   "]'),
(157, 'Siswa dikenakan biaya pendaftaran ulang pada setiap awal tahun pelajaran.', '["Tidak ada siswa yang dikenakan biaya pendaftaran ulang","1%-25% siswa dikenakan biaya pendaftaran ulang","26%-50% siswa dikenakan biaya pendaftaran ulang","51%- 75% siswa dikenakan biaya pendaftaran ulang","76%-100% siswa dikenakan biaya pendaftaran ulang "]'),
(158, 'Sekolah/madrasah dan/atau program keahlian memberikan bantuan untuk siswa yang kurang mampu secara ekonomi.', '["Membantu 91% -100% siswa kurang mampu secara ekonomi","Membantu 81% -90% siswa kurang mampu secara ekonomi","Membantu 71% -80% siswa kurang mampu secara ekonomi","Membantu 61% -70% siswa kurang mampu secara ekonomi","Membantu kurang dari 61% siswa kurang mampu secara ekonomi "]'),
(159, 'Sekolah/madrasah dan/atau program keahlian melakukan pungutan biaya personal selain uang sekolah/madrasah.', '["Tidak melakukan pungutan","Melakukan 1 jenis pungutan","Melakukan 2 jenis pungutan","Melakukan 3 jenis pungutan","Melakukan 4 jenis atau lebih pungutan   "]'),
(160, 'Pengambilan keputusan dalam penetapan dana dari masyarakat sebagai biaya personal dilakukan dengan melibatkan berbagai pihak terkait.', '["Melibatkan penyelenggara pendidikan/yayasan, kepala sekolah/ madrasah, komite sekolah/madrasah, perwakilan guru, perwakilan tenaga kependidikan","Melibatkan penyelenggara pendidikan/yayasan, kepala sekolah/ madrasah, komite sekolah/madrasah, dan perwakilan guru","Melibatkan penyelenggara pendidikan/yayasan, kepala sekolah/ madrasah dan komite sekolah/madrasah","Melibatkan penyelenggara pendidikan/yayasan dan kepala sekolah/madrasah","Hanya melibatkan kepala sekolah/madrasah "]'),
(161, 'Pengelolaan dana dari masyarakat sebagai biaya personal dilakukan secara transparan, efisien, dan akuntabel sesuai RKA-S/M.', '["91%-100% dana dari masyarakat tercantum dalam RKA-S/M","81%-90% dana dari masyarakat tercantum dalam RKA-S/M","71%-80% dana dari masyarakat tercantum dalam RKA-S/M","61%-70% dana dari masyarakat tercantum dalam RKA-S/M","Kurang dari 61% dana dari masyarakat tercantum dalam RKA-S/M "]'),
(162, 'Sekolah/Madrasah dan/atau program keahlian memiliki pedoman pengelolaan keuangan sebagai dasar dalam penyusunan RKA-S/M.', '["Memiliki pedoman pengelolaan keuangan selama 4 tahun terakhir secara berturut-turut","Memiliki pedoman pengelolaan keuangan selama 3 tahun terakhir secara berturut-turut","Memiliki pedoman pengelolaan keuangan selama 2 tahun terakhir secara berturut-turut","Memiliki pedoman pengelolaan keuangan selama 1 tahun terakhir secara berturut-turut","Tidak memiliki pedoman pengelolaan keuangan   "]'),
(163, 'Sekolah/Madrasah dan/atau program keahlian memiliki Buku Kas Umum (BKU).', '["Memiliki BKU yang diisi dengan benar selama 4 tahun terakhir","Memiliki BKU yang diisi dengan benar selama 3 tahun terakhir","Memiliki BKU yang diisi dengan benar selama 2 tahun terakhir","Memiliki BKU yang diisi dengan benar selama 1 tahun terakhir","Tidak memiliki BKU "]'),
(164, 'Sekolah/Madrasah dan/atau program keahlian membuat laporan pertanggungjawaban pengelolaan keuangan dan menyampaikannya kepada pemerintah atau yayasan.', '["Membuat laporan pertanggungjawaban pengelolaan keuangan dan menyampaikannya kepada pemerintah atau yayasan selama 4 tahun terakhir","Membuat laporan pertanggungjawaban pengelolaan keuangan dan menyampaikannya kepada pemerintah atau yayasan selama 3 tahun terakhir","Membuat laporan pertanggungjawaban pengelolaan keuangan dan menyampaikannya kepada pemerintah atau yayasan selama 2 tahun terakhir","Membuat laporan pertanggungjawaban pengelolaan keuangan dan menyampaikannya kepada pemerintah atau yayasan selama 1 tahun terakhir","Tidak membuat laporan pertanggungjawaban pengelolaan keuangan   "]'),
(165, 'Guru menginformasikan rancangan dan kriteria penilaian yang ada dalam silabus mata pelajaran kepada siswa pada semester yang berjalan.', '["96%-100% guru menginformasikan rancangan dan kriteria penilaian kepada siswa","91%-95% guru menginformasikan rancangan dan kriteria penilaian kepada siswa","86%-90% guru menginformasikan rancangan dan kriteria penilaian kepada siswa","81%-85% guru menginformasikan rancangan dan kriteria penilaian kepada siswa","Kurang dari 81% guru menginformasikan rancangan dan kriteria penilaian kepada siswa "]'),
(166, 'Teknik penilaian dalam silabus mata pelajaran produktif sesuai dengan indikator pencapaian kompetensi dasar (KD).', '["96%-100% silabus mata pelajaran produktif menggunakan teknik penilaian sesuai dengan indikator pencapaian KD","91%-95% silabus mata pelajaran produktif menggunakan teknik penilaian sesuai dengan indikator pencapaian KD","86%-90% silabus mata pelajaran produktif menggunakan teknik penilaian sesuai dengan indikator pencapaian KD","81%-85% silabus mata pelajaran produktif menggunakan teknik penilaian sesuai dengan indikator pencapaian KD","Kurang dari 81% silabus mata pelajaran produktif menggunakan teknik penilaian sesuai dengan indikator pencapaian KD   "]'),
(167, 'Guru mengembangkan instrumen dan pedoman penilaian sesuai dengan bentuk dan teknik penilaian.', '["96%-100% guru mengembangkan instrumen dan pedoman penilaian sesuai dengan bentuk dan teknik penilaian","91%-95% guru mengembangkan instrumen dan pedoman penilaian sesuai dengan bentuk dan teknik penilaian","86%-90% guru mengembangkan instrumen dan pedoman penilaian sesuai dengan bentuk dan teknik penilaian","81%-85% guru mengembangkan instrumen dan pedoman penilaian sesuai dengan bentuk dan teknik penilaian","Kurang dari 81% guru mengembangkan instrumen dan pedoman penilaian sesuai dengan bentuk dan teknik penilaian "]'),
(168, 'Guru menggunakan teknik penilaian sesuai dengan karakteristik mata pelajaran.', '["96%-100% guru menggunakan teknik penilaian sesuai dengan karakteristik mata pelajaran","91%-95% guru menggunakan teknik penilaian sesuai dengan karakteristik mata pelajaran","76%-80% guru menggunakan teknik penilaian sesuai dengan karakteristik mata pelajaran","61%-75% guru menggunakan teknik penilaian sesuai dengan karakteristik mata pelajaran","Kurang dari 61% guru menggunakan teknik penilaian sesuai dengan karakteristik mata pelajaran "]'),
(169, 'Guru mengolah hasil penilaian untuk mengetahui kemajuan hasil belajar dan kesulitan belajar siswa.', '["91%-100% guru mengolah hasil penilaian","81%-90% guru mengolah hasil penilaian","71%-80% guru mengolah hasil penilaian","61%-70% guru mengolah hasil penilaian","Kurang dari 61% guru mengolah hasil penilaian   "]'),
(170, 'Guru mengembalikan hasil pemeriksaan pekerjaan siswa disertai balikan/komentar yang mendidik.', '["96%-100% guru mengembalikan hasil pemeriksaan pekerjaan siswa disertai balikan/komentar","91%-95% guru mengembalikan hasil pemeriksaan pekerjaan siswa disertai balikan/komentar","86%-90% guru mengembalikan hasil pemeriksaan pekerjaan siswa disertai balikan/komentar","81%-85% guru mengembalikan hasil pemeriksaan pekerjaan siswa disertai balikan/komentar","Kurang dari 81% guru mengembalikan hasil pemeriksaan pekerjaan siswa disertai balikan/komentar "]'),
(171, 'Guru memanfaatkan hasil penilaian untuk perbaikan pembelajaran.', '["96%-100% guru memanfaatkan hasil penilaian","91%-95% guru memanfaatkan hasil penilaian","86%-90% guru memanfaatkan hasil penilaian","81%-85% guru memanfaatkan hasil penilaian","Kurang dari 81% guru memanfaatkan hasil penilaian "]'),
(172, 'Guru melaporkan hasil penilaian mata pelajaran pada setiap akhir semester kepada ketua program keahlian dalam bentuk laporan prestasi belajar siswa.', '["Seluruh guru melaporkan hasil penilaian prestasi belajar siswa","95%-99% guru melaporkan hasil penilaian prestasi belajar siswa","90%-94% guru melaporkan hasil penilaian prestasi belajar siswa","85%-89% guru melaporkan hasil penilaian prestasi belajar siswa","Kurang dari 85% guru melaporkan hasil penilaian prestasi belajar siswa "]'),
(173, 'Guru menilai sikap dan kepribadian siswa sebagai informasi untuk menentukan nilai akhir semester.', '["96%-100% guru menilai sikap dan kepribadian siswa","91%-95% guru menilai sikap dan kepribadian siswa","86%-90% guru menilai sikap dan kepribadian siswa","81%-85% guru menilai sikap dan kepribadian siswa","Kurang dari 81% guru menilai sikap dan kepribadian siswa   "]'),
(174, 'Guru mengkomunikasikan hasil penilaian kepribadian siswa kepada guru pendidikan kewarganegaraan sebagai informasi untuk menentukan nilai akhir semester.', '["96%-100% guru mengkomunikasikan hasil penilaian kepribadian siswa kepada guru pendidikan kewarganegaraan","91%-95% guru mengkomunikasikan hasil penilaian kepribadian siswa kepada guru pendidikan kewarganegaraan","86%-90% guru mengkomunikasikan hasil penilaian kepribadian siswa kepada guru pendidikan kewarganegaraan","81%-85% guru mengkomunikasikan hasil penilaian kepribadian siswa kepada guru pendidikan kewarganegaraan","Kurang dari 81% guru mengkomunikasikan hasil penilaian kepribadian siswa kepada guru pendidikan kewarganegaraan "]'),
(175, 'Ketua program keahlian mengkoordinasikan pelaksanaan: (1) ulangan tengah semester, (2) ulangan akhir semester, dan (3) ulangan kenaikan kelas.', '["Ketua program keahlian mengkoordinasikan pelaksanaan ulangan (1), (2), dan (3)","Ketua program keahlian mengkoordinasikan pelaksanaan (2) dan (3)","Ketua program keahlian mengkoordinasikan pelaksanaan ulangan (1) dan (3)","Ketua program keahlian hanya mengkoordinasikan pelaksanaan ulangan (3)","Tidak pernah mengkoordinasikan pelaksanaan ulangan "]'),
(176, 'Sekolah/madrasah dan program keahlian menentukan kriteria kenaikan kelas melalui rapat.', '["Menentukan kriteria melalui rapat dewan guru","Menentukan kriteria melalui rapat dengan perwakilan guru-guru mata pelajaran","Menentukan kriteria melalui rapat dengan wali kelas saja","Menentukan kriteria melalui rapat pimpinan sekolah","Hanya ditetapkan oleh kepala sekolah/madrasah   "]'),
(177, 'Sekolah/Madrasah menentukan nilai akhir kelompok mata pelajaran agama dan akhlak; kewarganegaraan dan kepribadian; estetika; serta jasmani, olahraga, dan kesehatan.', '["Menentukan nilai akhir melalui rapat dewan guru dengan mempertimbangkan hasil penilaian oleh guru","Menentukan nilai akhir melalui rapat dewan guru tanpa mempertimbangkan hasil penilaian oleh guru","Menentukan nilai akhir tanpa melalui rapat dewan guru tetapi mempertimbangkan hasil penilaian oleh guru","Menentukan nilai akhir oleh wali kelas","Hanya ditetapkan oleh kepala sekolah/madrasah "]'),
(178, 'Sekolah/madrasah menyelenggarakan ujian semester sesuai Prosedur Opersional Standar (POS).', '["Memiliki POS dan dilaksanakan sesuai POS","Memiliki POS tetapi tidak dilaksanakan sesuai POS","Menyelenggarakan ujian tetapi tidak memiliki POS","Menyelenggarakan ujian hanya oleh masing-masing guru","Tidak menyelenggarakan ujian "]'),
(179, 'Program keahlian menyampaikan hasil penilaian dan penjelasan setiap akhir semester kepada orang tua/wali siswa.', '["Menyampaikan hasil penilaian dan penjelasan kepada orangtua/wali siswa, dan siswa yang bersangkutan","Menyampaikan hasil penilaian dan penjelasan kepada orangtua/wali siswa tanpa siswa yang bersangkutan","Menyampaikan hasil penilaian dan penjelasan kepada siswa yang bersangkutan","Menyampaikan hasil penilaian tanpa penjelasan kepada orangtua/wali siswa","Menyampaikan hasil penilaian tanpa penjelasan kepada siswa bersangkutan   "]'),
(180, 'Sekolah/madrasah melaporkan pencapaian hasil belajar siswa kepada Dinas Pendidikan Provinsi atau Kanwil Kemenag.', '["Melaporkan pencapaian hasil belajar siswa kurang dari 20 hari setelah akhir semester","Melaporkan pencapaian hasil belajar siswa antara 21 — 40 hari setelah akhir semester","Melaporkan pencapaian hasil belajar siswa antara 41 — 60 hari setelah akhir semester","Melaporkan pencapaian hasil belajar siswa antara 61 — 80 hari setelah akhir semester","Melaporkan pencapaian hasil belajar siswa lebih dari 80 hari "]'),
(181, 'Sekolah/madrasah dan program keahlian menentukan kelulusan sesuai pedoman ketentuan kelulusan siswa dari satuan pendidikan.', '["Menentukan kelulusan siswa melalui rapat dewan guru","Menentukan kelulusan siswa melalui rapat dengan perwakilan guruguru mata pelajaran","Menentukan kelulusan siswa melalui rapat dengan wali kelas saja","Menentukan kelulusan siswa melalui rapat pimpinan sekolah/madrasah","Hanya ditetapkan oleh kepala sekolah/madrasah "]'),
(182, 'Sekolah/madrasah menyerahkan Surat Keterangan Hasil Ujian Nasional (SKHUN) setiap siswa yang mengikuti Ujian Nasional (UN).', '["Menyerahkan SKHUN kurang dari 7 hari setelah diterima dari Dinas Pendidikan/Kanwil Kemenag Provinsi","Menyerahkan SKHUN antara 8-14 hari setelah diterima dari Dinas Pendidikan/Kanwil Kemenag Provinsi","Menyerahkan SKHUN antara 15-21 hari setelah diterima dari Dinas Pendidikan/Kanwil Kemenag Provinsi","Menyerahkan SKHUN antara 22-35 hari setelah diterima dari Dinas Pendidikan/Kanwil Kemenag Provinsi","Menyerahkan SKHUN lebih dari 35 hari setelah diterima dari Dinas Pendidikan/Kanwil Kemenag Provinsi   "]'),
(183, 'Sekolah/madrasah menerbitkan dan menyerahkan ijazah kepada setiap siswa yang telah lulus.', '["Kurang dari 7 hari setelah blangko ijazah diterima dari Dinas Pendidikan/Kandepag","Antara 8 — 14 hari setelah blangko ijazah diterima dari Dinas Pendidikan/Kandepag","Antara 15 — 21 hari setelah blangko ijazah diterima dari Dinas Pendidikan/Kandepag.","Antara 22 — 28 hari setelah blangko ijazah diterima dari Dinas Pendidikan/Kandepag","Lebih dari 28 hari setelah blangko ijazah diterima dari Dinas Pendidikan/Kandepag "]'),
(184, 'Sekolah/madrasah dan/atau program keahlian menggunakan hasil Ujian Nasional (UN) SMP/MTs/ Ujian Nasional Pendidikan Kesetaraan (UNPK) Program Paket B sebagai bahan pertimbangan penerimaan siswa baru.', '["Menggunakan hasil UN SMP/MTs/Paket B dan seleksi masuk secara transparan sebagai bahan pertimbangan penerimaan siswa baru","Menggunakan hasil UN SMP/MTs/Paket B secara transparan sebagai bahan pertimbangan penerimaan siswa baru","Menggunakan hasil UN SMP/MTs/Paket B dan seleksi masuk secara tidak transparan sebagai bahan pertimbangan penerimaan siswa baru","Menggunakan hasil UN SMP/MTs/Paket B secara tidak transparan sebagai bahan pertimbangan penerimaan siswa baru","Tidak menggunakan UN SMP/MTs/Paket B sebagai bahan pertimbangan penerimaan siswa baru "]'),
(185, 'Program keahlian melaksanakan uji kompetensi siswa sesuai kompetensi keahliannya melibatkan pihak lain yang terkait.', '["Melibatkan pihak Lembaga Sertifikasi Profesi (LSP) atau asosiasi profesi yang sesuai dengan kompetensi keahlian","Melibatkan pihak perusahaan atau industri yang sesuai dengan kompetensi keahlian","Melibatkan guru produktif dari satuan pendidikan lain yang sesuai dengan kompetensi keahlian","Melibatkan guru produktif dalam satuan pendidikan sendiri","Tidak melaksanakan uji kompetensi"]');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
`id` int(10) unsigned NOT NULL,
  `uname` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `group_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `uname`, `password`, `remember_token`, `group_id`, `created_at`, `updated_at`) VALUES
(1, 'admin', '$2y$10$KeZxLonxPqP20rYn9pfk/Oo.fteg/HV/KzLdzUPlXpy0hcWXTtIcm', 'ya3qoDR6pus1OgKmqMPAYe83Ysi9KSaOagIOAIhLC4UJSXH1wkpEe5ZB1Mrv', 1, '2015-05-10 12:26:42', '2015-09-16 07:32:29'),
(2, 'asesor', '$2y$10$9FnGiwSyaqfx/sF9CFc8qeD8fBGmvcb6yoUsLby6usTF2lKIm5uKG', 'SBQSws4hFr4bVZJaTnh6fXQbz1gQ1eUqVPXpwVVhtBszbFSsHcyr9cMiSGGQ', 2, '2015-05-10 12:26:42', '2015-09-16 07:21:21'),
(5, 'satu', '$2y$10$OUuh6BPz0S.L1LQ04IErve0Y4QFulRmuTs5P3t/sM6SEPkwgnulwa', 'uXYidBUtQPZBi5m889ojSOnAi7iHx2gK5WTAvMwPiewlMXOdvUGawQQs9J1j', 3, '2015-05-25 01:50:39', '2015-09-11 20:51:29'),
(6, 'dua', '$2y$10$tWJcRclcJJGNN5JEUZFBaO8znZU8YY4w2F0GQVzYFeP5dyOaqYUNq', 'SgHOBdi4EtJWxRPyEU8kjs6e3zo7HfcsfLfJAR6mJRgbtni5VNNxppb5IP2G', 3, '2015-05-25 01:50:39', '2015-09-16 07:31:41'),
(7, 'tiga', '$2y$10$lCtdTaMeATSKVoqZEGJjl.ENPLwmvYTFFA7HCdP7LDMAJNzLV/qVy', 'AkfKW4TnmJUG4zRerN91cEAM1Ndj4HPdHTIJ1Cm3O0HZWBbRyTq7UIy6y2gC', 3, '2015-05-25 01:50:39', '2015-09-13 07:20:13'),
(8, 'empat', '$2y$10$FIGO6Wx/6dHRTIlaVZmC1.LcBwbzStndcFSRJc3YgPK6nLR3gEboq', 'rdRJNJbjbZHUV871iwonkHg4SiBqroCb5GmALTUoWlCEIpl0cyh5y5nF0uli', 3, '2015-05-25 01:50:39', '2015-09-11 21:45:40'),
(22, 'dayan', '$2y$10$Yvyy2u96zRVqbBwTy6HA1e7Ta.OAAzXyJemjlOYklf9tpMCltncCW', NULL, 3, '2015-09-14 17:44:24', '2015-09-14 17:44:24'),
(23, 'thori', '$2y$10$j8d6p4bGzP8tTLH1VT.GIuzsqp2katjdIhrZwB4AjU4jLdqtrtmkW', NULL, 3, '2015-09-14 17:45:15', '2015-09-14 17:45:15'),
(24, 'damar', '$2y$10$8PIkPejHD67xgH3tEv0Bo.ebF0LajLwMjMsuHUiGWs6qaLqTSeVJC', NULL, 3, '2015-09-14 17:45:55', '2015-09-14 17:45:55'),
(25, 'smkblala', '$2y$10$VQp1ImgftvaVJSRXNratP.8fN8wWnTvkYPTDa40ihs.wA39RGmlIS', NULL, 3, '2015-09-14 17:59:02', '2015-09-14 17:59:02'),
(26, 'h', '$2y$10$h1LF1oypQPKHVSt1yyiEQOwq398OxRTlnTyI2itAnHnrIxU4l/72S', NULL, 3, '2015-09-14 17:59:19', '2015-09-14 17:59:19'),
(27, 'andi', '$2y$10$YasowPwfy63Txj9.YLah8ezRc1sTnZqcm0XQFFtkQ71vqWjg/tQZO', 'pQR7kwCFGFq5N2z3DvWmGeVPNQ3BySWoPpVW9Ya9cqatTPB0O8AuGXd6zxMC', 3, '2015-09-15 17:23:41', '2015-09-15 17:24:01'),
(30, 'thoriq', '$2y$10$o54gWYk31qdpWaA.ZwkFtuO4uvhd6fqdRRsWoZmbo4YWFDePZ0LgO', NULL, 3, '2015-09-15 18:38:04', '2015-09-15 18:38:04');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `group`
--
ALTER TABLE `group`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `name_UNIQUE` (`nama`);

--
-- Indexes for table `identitas`
--
ALTER TABLE `identitas`
 ADD PRIMARY KEY (`id`), ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `jawaban`
--
ALTER TABLE `jawaban`
 ADD PRIMARY KEY (`id`), ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `pertanyaan`
--
ALTER TABLE `pertanyaan`
 ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `uname_UNIQUE` (`uname`), ADD KEY `fk_user_group_idx` (`group_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `group`
--
ALTER TABLE `group`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `identitas`
--
ALTER TABLE `identitas`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=9;
--
-- AUTO_INCREMENT for table `jawaban`
--
ALTER TABLE `jawaban`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `pertanyaan`
--
ALTER TABLE `pertanyaan`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=186;
--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=31;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `identitas`
--
ALTER TABLE `identitas`
ADD CONSTRAINT `identitas_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `jawaban`
--
ALTER TABLE `jawaban`
ADD CONSTRAINT `jawaban_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `user`
--
ALTER TABLE `user`
ADD CONSTRAINT `fk_user_group` FOREIGN KEY (`group_id`) REFERENCES `group` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
